### ISSUE TITLE
virtualmin backups with ssh on an alternative port number

### ISSUE THREAD

**Issue by gstlouisgit** [virtualmin/virtualmin-install#102]
I tried testing out the ssh backups
I'm going to assume this is a scp call to send the files over.  In the SSH Server field, it shows that you can specify the port, and my port is 6969, so I put in domain.hopto.org:6969

<img width="781" alt="Screen Shot 2024-01-24 at 12 46 45 PM" src="https://github.com/virtualmin/virtualmin-install/assets/20375753/b8eebe71-ed1d-4e8e-8550-cdb584b132bc">

Then I put in the path, with and without the trailing slash at the end for folder.  tried also playing with the varibale date options etc.

<img width="563" alt="Screen Shot 2024-01-24 at 12 47 40 PM" src="https://github.com/virtualmin/virtualmin-install/assets/20375753/2455420a-0721-43dc-86e6-0ecaa06e2300">

It didn't work for me and I got this error.  Do note, I've tested scp at the terminal from that box and ensured this is not a password problem.  You will see however the last comment of "lost connection".  So I'm thinking I'm doing something wrong in the field settings or this might not be working with an alternative port?

The error 
Testing backup destination /mnt/backups/virtualmin.backups on SSH server domain.hopto.org ..
Failed to connect to SSH server : root@domain.hopto.org's password: Permission denied, please try again. root@domain.hopto.org's password: Permission denied, please try again. root@domain.hopto.org's password: root@domain.hopto.org: Permission denied (publickey,password). lost connection

**Comment by jcameron** [comment]
It does look like the password isn't being accepted.

Does the destination server also run SSH on port 22? Because if Virtualmin wasn't using the correct port, you would get a "connection refused" error instead of "permission denied".

**Comment by gstlouisgit** [comment]
You are correct.  It was the password.  Sorry to have wasted your time Jamie.  I swear last night I typed it and copied and pasted it.  I just did a copy past of the password and its working.  sorry man

**Comment by jcameron** [comment]
Ok, no worries!
