### ISSUE TITLE
Virtualmin installer doesn't present the correct IP address

### ISSUE THREAD

**Issue by Bt6K** [virtualmin/virtualmin-install#103]
Hi,

I installed Virtualmin on an AlmaLinux 8 VPS, powered by OpenVZ 7.

It installed fine, but I noticed a small issue:

```
[SUCCESS] Installation Complete!
[SUCCESS] If there were no errors above, Virtualmin should be ready
[SUCCESS] to configure at https://test.test.com:10000 (or https://127.0.0.1:10000).
[SUCCESS] You may receive a security warning in your browser on your first visit.
```

Notice how the IP address is being reported as 127.0.0.1

Can this be fixed?

Here is the full install log: https://pastebin.com/raw/uuTgeM6G

Thanks

**Comment by iliajie** [comment]
Hello,

> Notice how the IP address is being reported as 127.0.0.1
> 
> Can this be fixed?

Check your `/etc/hosts` file.

**Comment by iliajie** [comment]
Given the content of `/etc/hosts` file, Virtualmin does everything right &mdash; there is no bug for us to address.
