### ISSUE TITLE
Virtualmin installer complaints about unknown package not being installed.

### ISSUE THREAD

**Issue by Bt6K** [virtualmin/virtualmin-install#105]
Hi,

I installed Virtualmin on an AlmaLinux 8 VPS, powered by OpenVZ 7.

It installed fine, but I noticed a small issue:

```
Phase 2 of 4: Setup
Installing core plugins for package manager                                  OK
Downloading Virtualmin 7 release package                                     OK
error: package  is not installed
Installing Virtualmin 7 release package                                      OK
```

In particular: **error: package  is not installed**

Yet, it doesn't specify _which_ package is not installed. 

Here is the full install log: https://pastebin.com/raw/uuTgeM6G

**Comment by iliajie** [comment]
Hi,

It doesn't seem like a problem, as the package was eventually installed. The error in the log means that other process was managing packages.

**Comment by exp0logy** [comment]
As mentioned above @Bt6K the line in your install

'error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Resource temporarily unavailable)'

Signifies something else was installing at that time (System Updates or alike).
This issue can be closed.
