### ISSUE TITLE
error 100 on ubuntu 22.04

### ISSUE THREAD

**Issue by nasermars** [virtualmin/virtualmin-install#106]
Hi, I tried to install VM on ubuntu 22.04 by script. 
In phase 3, checking, after a lot of times, give error 100.
I tried many times and different methods, but I cannot install it.

**Comment by iliajie** [comment]
Hello,

I have tried installing on Ubuntu 22.04 and everything worked just fine!

What exact error are you seeing; can you provide a screenshot of an error?

Also, what is logged to `virtualmin-install.log` file? Have you tried running the following before installation and seeing if it works in the first place?

```
apt-get update
apt-get upgrade -y
```

Furthermore, is this clean minimal installation of Ubuntu 22.04?

**Comment by nasermars** [comment]
hi,
I update and upgrade the server. Then tried to install virtualmin. I used a normal installation method (not minimal) and used LEMP bundle (nginx). On this server RAM = 6 G and CPU = 2 core.
I installed virtualmin on other servers and were easy :).

Installation error:
```
▣▣◻◻ Phase 2 of 4: Setup
[ERROR] Your system hostname irvm-669134 is not fully qualified.
Please enter a fully qualified hostname (e.g.: host.example.com): ns5.mydomain.com
Downloading Virtualmin 7 key                                                 ✔
Installing Virtualmin 7 key                                                  ✔
Downloading repository metadata                                             [ERROR] Failed with error: 100
 ✘

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:4 https://software.virtualmin.com/vm/7/gpl/apt virtualmin InRelease [10.7 kB]
Hit:5 http://de.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:7 https://software.virtualmin.com/vm/7/gpl/apt virtualmin/main all Packages [20.8 kB]
Get:9 https://software.virtualmin.com/vm/7/gpl/apt virtualmin/main amd64 Packages [20.8 kB]
Get:6 http://mirrors.edge.kernel.org/ubuntu xenial InRelease [247 kB]
Hit:8 https://packagecloud.io/ookla/speedtest-cli/ubuntu jammy InRelease
Err:6 http://mirrors.edge.kernel.org/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
Reading package lists...
W: GPG error: http://mirrors.edge.kernel.org/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://mirrors.kernel.org/ubuntu xenial InRelease' is not signed.
Downloading repository metadata: [2024-05-02 17:49:20 UTC] [ERROR] Failed with error: 100
[2024-05-02 17:49:20 UTC] [ERROR] Something went wrong. Exiting.
[2024-05-02 17:49:20 UTC] [ERROR] The last few log entries were:
```

VM.log:
```
Downloading Virtualmin 7 key: Success.
Spin pid is: 32319
gpg: key 3E570892B9A0B8B7: "Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Installing Virtualmin 7 key: Success.
Spin pid is: 32340
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
... is like putty error.
```

**Comment by iliajie** [comment]
> E: The repository 'http://mirrors.kernel.org/ubuntu xenial InRelease' is not signed.

You should look into solving this error first, which is not a Virtualmin issue to be clear.

**Comment by nasermars** [comment]
Solved!
The main problem was my VPS server and it's connection (yesterday). I find it today.
I send above feedback and I think it maybe useful!

Today I changed my server and IP and installed at the second try (after solving KEY problem as you mentions).

Thank you for your responsive. 
Since I learned to use Virtualmin, I hate other panels (like cpanel, ...) and introduce to others. It's very simple, but some difficulty to use on wordpress may need to solve (I will comment next).

Bests

**Comment by iliajie** [comment]
> and introduce to others. It's very simple, but some difficulty to use on wordpress may need to solve (I will comment next).

Thanks!

We're actually working right now on making WordPress experience smoother!

If you have any suggestions related to WordPress, now would be a great time to share them with us! 🙂

**Comment by nasermars** [comment]
A few comments for wordpress:
**database management**: we cannot change user (admin) password by db access, because we haven't MD5 method (table users in wordpress db).
**emailing**: first time I cannot find income/outcome emails! In fact, where are them??? Yes I know that I must install it's Script. But it is good to easy access to emails platform. Also, creating email user, webmin user, ... is a little difficult (we cannot distinguish them). I think that "one user then one email account" on webmin and when login, directly access to emails on VM dashboard (not webmin -> read mail)
**Host**: Oh excuse me, virtual server. Domain? No, virtual server :) :(
**DKIM**: For beginners is too hard that they cannot send email to gmail, yahoo, ... . Maybe need to install it in VM default modules.
**URLs**: When I use permalink on other methods (not wordpress plain method), it not work! At the most times we install wordpress by a theme that we bought (we did not install by VM script). So the links on Custom Structure not work correctly. This change maybe is good for laravel or others.
**REST api**: Sometimes not work correctly.
php: mostly we need php Modules! For example, if php-zip library not installed on server, it make a lot of problems and founding it is very hard. VM can install at the first time based on wordpress recommended php-Modules . As a guide: intl, curl, gd, ... .
**upload size** (php, nginx): maybe it's time to increase upload size to minimum 16 MB :)

**Comment by iliajie** [comment]
Thanks for your suggestions! We will address it!

If you come up with something else please let us know!

**Comment by nasermars** [comment]
A few more about wordpress:
**Default email**: One other important thing is `wordpress@mydomain.com` email as wordpress default email. When we install wordpress, wordpress email must be define and work by default! As new user (also old user), I don't want to define it. All website error emails will send by this email. If not active, then we cannot recover password, issues, etc.
**Cloadflare**: recently I have a problem by cloadflare CDN I think an automatic subdomain or **SSL** certificate have issue. I test more times but I cannot find the solving. Of course maybe you cannot find on simple wordpress, but other themes and plugins have need more modules. We need to work it on Cloadfalre simple ssl system (on flexible). Sometimes it work on "full".
**Database interface**:  I want to import my database to server. Hooray there is an import tab! But when you go to "Import" tab, there is no option to import mydb.sql file. Where is it?? Yes I have to go "manage" option. But Where is "Import "option? Oh yes, I have to go "Execute SQL" and then go to "Run SQL from file" tab and then then choose file then ... (maybe zip file not import and must use .sql file only). I mean, the processes are confusing and not simple to import/recover database. Maybe create a simple tab on first page (on db manager) be good idea. 
Another idea is to install "**phpmydamin**" script by default and make a tab or simple option on interface that redirect it to phpmyadmin. Also I think "**RoundCube** " for emailing is good idea for access easily.

**Comment by iliajie** [comment]
Thanks, we'll consider some of your suggestions!

> Another idea is to install "**phpmydamin**" script by default and make a tab or simple option on interface that redirect it to phpmyadmin. Also I think "**RoundCube** " for emailing is good idea for access easily.

Why stop there? 😄 Let's throw in a toaster control panel too; nothing complements WordPress management like a perfectly browned bagel!
