### ISSUE TITLE
LEMP stack wants to install apache2, breaking websites.

### ISSUE THREAD

**Issue by dronus** [virtualmin/virtualmin-install#107]
The newest version of LEMP stack does provide a bad virtualmin-lemp-stack 7.0.5-1 metapackage, which accidentally (?) depends on apache2.

The apache2 package does provide an apache2 service, that is enabled by default. Installing this package enables the apache2 server, which in turn prevents nginx from claiming the ports. Finally all users see apache greeter webpages, as there is no virtual host config of course.

I've put the package on hold by `apt-mark hold  virtualmin-lemp-stack` on an older version, but on machines where the update is already done damage is done, and the package need to be rolled back and apache removed.

**Comment by iliajie** [comment]
This issue was fixed!

Thanks for the heads up!

**Comment by iliajie** [comment]
> I've put the package on hold by `apt-mark hold virtualmin-lemp-stack` on an older version, but on machines where the update is already done damage is done, and the package need to be rolled back and apache removed.

Apologies for that!
