### ISSUE TITLE
Installer script returns exit code 1 on success

### ISSUE THREAD

**Issue by 000host** [virtualmin/virtualmin-install#108]
Hello,

We've noticed that the installer returns exit status code 1 on successful installation. 

> [SUCCESS] Installation Complete!
> [SUCCESS] If there were no errors above, Virtualmin should be ready
> [SUCCESS] to configure at https://virtualmin.vps:10000 (or https://redacted.for.privacy:10000).
> [SUCCESS] You may receive a security warning in your browser on your first visit.
> root@localhost:~# echo $?
> 1

OS: Debian 12
CMD: `/root/virtualmin-install.sh --bundle LEMP --force --hostname virtualmin.vps`

The expected result is exit code 0, and from the installer source, we believe that return 0 is the desired value. 
So perhaps this is something worth checking out. In manual installation this is not an issue in any way, however in automated installations, this limits our capabilities for proper error detection etc.  

[virtualmin-install.log](https://github.com/virtualmin/virtualmin-install/files/15377101/virtualmin-install.log)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! We will [fix it](https://github.com/virtualmin/slib/commit/ceb6add8ab50a24dc9bb675aecf44ccbcf75696a) in the next release.
