### ISSUE TITLE
software.virtualmin.com SSL certificate expired

### ISSUE THREAD

**Issue by longz3r** [virtualmin/virtualmin-install#110]
The domain software.virtualmin.com SSL certificate expired which make repository index can not be retrieved easily (even with -i flag)
![image](https://github.com/user-attachments/assets/6044ab1c-bca3-4488-ad7b-78a13897dd48)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! We will fix this as soon as possible and update this ticket with progress.

**Comment by iliajie** [comment]
This issue has been fixed!

Thanks!
