### ISSUE TITLE
Repository setup modification required and No Public Key available on Import.

### ISSUE THREAD

**Issue by timothygwebb** [virtualmin/virtualmin-install#114]
To Whom It May Concern:  I have fixed this issue on my local.

![image](https://github.com/user-attachments/assets/5e91633d-2df8-4956-8117-72249496d7ce)
![image](https://github.com/user-attachments/assets/c66b9f6f-2cb5-41d4-91e3-ea4daced62ee)
![image](https://github.com/user-attachments/assets/5d8dec10-8769-4fdd-9d6f-d9e7628230ca)

The issue was that the configuration in /etc/apt/sources.list.d/
RE https://forum.virtualmin.com/t/virtualmin-apt-update-problems/129093/5 

Part of the issue I was having was the following. 

pub   rsa4096 2017-05-01 [SC] [expired: 2024-04-29]
      E36F 0664 7D8E BD2B E364  2BCE D9F9 0107 60D6 2A6B
uid           [ expired] Virtualmin, Inc. (Package signing key for Virtualmin 6) <security@virtualmin.com>

sudo apt-key del "[ expired] Virtualmin, Inc. (Package signing key for Virtualmin 6) <security@virtualmin.com>"
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

sudo apt-key add RPM-GPG-KEY-virtualmin-7.gpg
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

pub   rsa4096 2022-01-08 [SC] [expires: 2029-01-06]
      586C 427B 9590 C1C4 35A5  FE39 3E57 0892 B9A0 B8B7
uid           [ unknown] Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>
sub   rsa4096 2022-01-08 [E] [expires: 2029-01-06]

The installer script is adding keys into the apt-key repository for both 6 and 7 this is a failure on the script and its actions. 

Checking for HTTP client .. found /usr/bin/wget -nv
2024-11-25 00:06:54 URL:https://software.virtualmin.com/lib/slib.sh [24222/24222] -> "slib.sh" [1]
[2024-11-25 00:06:54 EST] [INFO] Log will be written to: /home/timothywebbsr/Downloads/virtualmin-install.log
[2024-11-25 00:06:54 EST] [DEBUG] LOG_ERRORS_FATAL=1
[2024-11-25 00:06:54 EST] [DEBUG] LOG_LEVEL_STDOUT=INFO
[2024-11-25 00:06:54 EST] [DEBUG] LOG_LEVEL_LOG=DEBUG
Checking for Perl .... found Perl at /usr/bin/perl
Checking for HTTP client .. found /usr/bin/wget -nv
Checking for GPG .. found GPG command
[2024-11-25 00:06:54 EST] [INFO] Started Virtualmin 7 GPL software repositories setup
[2024-11-25 00:06:54 EST] [DEBUG] Install mode: setup
[2024-11-25 00:06:54 EST] [DEBUG] Product: Virtualmin GPL
[2024-11-25 00:06:54 EST] [DEBUG] virtualmin-install.sh version: 7.4.0
[2024-11-25 00:06:54 EST] [DEBUG] Installing serial number and license key into /etc/virtualmin-license
[2024-11-25 00:06:55 EST] [DEBUG] Operating system name:    Ubuntu
[2024-11-25 00:06:55 EST] [DEBUG] Operating system version: 24.10
[2024-11-25 00:06:55 EST] [DEBUG] Operating system type:    ubuntu
[2024-11-25 00:06:55 EST] [DEBUG] Operating system major:   24
[2024-11-25 00:06:55 EST] [DEBUG] Configuring package manager for Ubuntu 24.10 ..
[2024-11-25 00:06:55 EST] [DEBUG] apt-get repos: virtualmin
[2024-11-25 00:06:55 EST] [DEBUG] Installing Webmin and Virtualmin package signing keys ..
Spin pid is: 3057688
2024-11-25 00:06:55 URL:https://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-7 [3212/3212] -> "RPM-GPG-KEY-virtualmin-7" [1]
Downloading Virtualmin 7 key: Success.
Spin pid is: 3057732
gpg: key 3E570892B9A0B8B7: "Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Installing Virtualmin 7 key: Success.
Spin pid is: 3057758
**_### E: Conflicting values set for option Signed-By regarding source https://software.virtualmin.com/vm/7/gpl/apt/ virtualmin: /usr/share/keyrings/ubuntu-virtualmin-7.gpg != /usr/share/keyrings/RPM-GPG-KEY-virtualmin-7.gpg_**
E: The list of sources could not be read.
Downloading repository metadata: [2024-11-25 00:06:57 EST] [ERROR] Failed with error: 100
[2024-11-25 00:06:57 EST] [ERROR] Something went wrong. Exiting.
[2024-11-25 00:06:57 EST] [ERROR] The last few log entries were:

![Screenshot_2024-11-25_00-19-55](https://github.com/user-attachments/assets/e5b82af5-b32a-4108-9283-657315026e9b)

pub   rsa4096 2017-05-01 [SC] [expired: 2024-04-29]
      E36F 0664 7D8E BD2B E364  2BCE D9F9 0107 60D6 2A6B
uid           [ expired] Virtualmin, Inc. (Package signing key for Virtualmin 6) <security@virtualmin.com>

pub   rsa4096 2022-01-08 [SC] [expires: 2029-01-06]
      586C 427B 9590 C1C4 35A5  FE39 3E57 0892 B9A0 B8B7
uid           [ unknown] Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>
sub   rsa4096 2022-01-08 [E] [expires: 2029-01-06]

As noted in the referenced web page this does not resolve the issue. The reason being can be found in the screenshot attached the key that cannot be verified is a sub key on the signature that is being validated and this must be rectified.

The rest of the conversation is on supporting 24.10+ versions with the mandatory repository structure updates. 

I would like to contribute the required information to help in updating the installer and repository script setup. 

This is the new repository that will allow you to support 24.10+

The below is a snippet of the code requirements that would need to be modified.

However I do understand that the script has these items stored in variables. 

With this said there are many areas of the script that would need to have this information updated due to the $vm6_repos in the script with the binary selections on whether or not it is used along with the $vm_version and os. 

Script execution after manual required updates.

Get: 7 https://software.virtualmin.com/vm/7/gpl/apt virtualmin InRelease [10.7 kB]
Err https://software.virtualmin.com/vm/7/gpl/apt virtualmin InRelease       
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E570892B9A0B8B7
W: Failed to fetch https://software.virtualmin.com/vm/7/gpl/apt/dists/virtualmin/InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3E570892B9A0B8B7

Here are just a few of the required script updates I had to reverse engineer and or update to get it to begin working.

 # Install our keys
    log_debug "Installing Webmin and Virtualmin package signing keys .."
    download "https://$upgrade_virtualmin_host/lib/RPM-GPG-KEY-virtualmin-$vm_version" "Downloading Virtualmin $vm_version key"
    run_ok "gpg --import RPM-GPG-KEY-virtualmin-$vm_version && cat RPM-GPG-KEY-virtualmin-$vm_version | gpg --dearmor > /usr/share/keyrings/debian-virtualmin-$vm_version.gpg" "Installing Virtualmin $vm_version key"
    download "https://$upgrade_virtualmin_host/lib/RPM-GPG-KEY-webmin" "Downloading Webmin key"
    run_ok "gpg --import RPM-GPG-KEY-webmin && cat RPM-GPG-KEY-webmin | gpg --dearmor > /usr/share/keyrings/debian-webmin.gpg" "Installing Webmin key"

ubuntu)
      if [ "$os_version" != "18.04" ] && [ "$os_version" != "20.04" ] && [ "$os_version" != "22.04" ] && [ "$os_version" != "24.04" ]&& [ "$os_version" != "24.10" ]; 
      then
        printf "${RED}${os_real} ${os_version} is not supported by this installer.${NORMAL}\\n"
        exit 1

24.10*)
          repos="Types: deb deb-src
				URIs: https://software.virtualmin.com/vm/7/gpl/apt
				Suites: virtualmin
				Components: main
				Signed-By: /usr/share/keyrings/RPM-GPG-KEY-virtualmin-7.gpg"

With that being said I have went to the extent to validate the signatures and public key availability which is not available by doing the following from the InRelease signature.
 
gpg --include-key-block --auto-key-import InRelease
gpg: Signature made Sun 18 Aug 2024 12:49:05 AM EDT
gpg:                using RSA key 586C427B9590C1C435A5FE393E570892B9A0B8B7
gpg: Good signature from "Virtualmin, Inc. (Package signing key for Virtualmin 7) <security@virtualmin.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 586C 427B 9590 C1C4 35A5  FE39 3E57 0892 B9A0 B8B7

They sub keys  are not expired so I do not understand why they public key is not available.  The screenshot below shows the non expired sub keys that are trying to be validated by the public key which is not available. 

I have attached the below screenshots for proof of successful checks on a 24.10+ system using Oracular Oriole.

Let me know your thoughts on how the team would like to incorporate this information.

![Screenshot_2024-11-24_21-47-33](https://github.com/user-attachments/assets/6000b70e-7f22-4878-a63e-ee7331930332)

![Screenshot_2024-11-24_21-31-24](https://github.com/user-attachments/assets/0b4b8a7f-cf75-4b47-b78b-9caf13944e7d)

Output from request to reinstall some are available and some are not due to the sub key validation issue.

sudo apt install --reinstall *virtualmin*
Note, selecting 'webmin-virtualmin-init' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-sqlite' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-styles-oswd' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-awstats' for glob '*virtualmin*'
Note, selecting 'virtualmin-config' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-messageoftheday' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-htpasswd' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-vsftpd' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-iframe' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-notes' for glob '*virtualmin*'
Note, selecting 'virtualmin-base' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-registrar' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-powerdns' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-password-recovery' for glob '*virtualmin*'
Note, selecting 'virtualmin-core' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-nginx-ssl' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-slavedns' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-dav' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-nginx' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-git' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-support' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-mailrelay' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-google-analytics' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-svn' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-oracle' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-multi-login' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-signup' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-disable' for glob '*virtualmin*'
Note, selecting 'webmin-virtualmin-mailman' for glob '*virtualmin*'
Reinstallation of virtualmin-config is not possible, it cannot be downloaded.
Reinstallation of virtualmin-core is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-awstats is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-htpasswd is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-dav is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-disable is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-git is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-google-analytics is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-iframe is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-init is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-mailman is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-mailrelay is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-messageoftheday is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-multi-login is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-nginx is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-nginx-ssl is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-notes is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-oracle is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-password-recovery is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-powerdns is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-registrar is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-signup is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-slavedns is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-sqlite is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-styles-oswd is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-support is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-svn is not possible, it cannot be downloaded.
Reinstallation of webmin-virtualmin-vsftpd is not possible, it cannot be downloaded.
Summary:
  Upgrading: 0, Installing: 0, Removing: 0, Not Upgrading: 0

**Comment by timothygwebb** [comment]
> Hello,
> 
> We don’t support non-LTS Ubuntu releases, as they’re not really suitable for servers or production enterprise environments. This has always been the case, though we might consider supporting it as a Grade B system.

Thanks for letting me know. I would like to know more about this Grade B system and if I could be of any assistance.

**Comment by iliajie** [comment]
> I would like to know more about this Grade B system and if I could be of any assistance.

https://www.virtualmin.com/docs/os-support

**Comment by timothygwebb** [comment]
> > I would like to know more about this Grade B system and if I could be of any assistance.
> 
> https://www.virtualmin.com/docs/os-support

@iliajie Thank you for the response. This system would be a great B system to support. I have been able to use the script and modify needed parameters as documented in the referenced document. Let me know if you would like more information on what I do with my system. I take it by your documentation you would consider me an expert in my area. 👍🏻

Here are the specs of my environment.

Operating system Ubuntu Linux 24.10
Webmin version 2.202
Usermin version 2.102
Virtualmin version 7.20.2  
Authentic theme version 21.20.7
Kernel and CPU Linux 6.11.0-9-generic on x86_64
Processor information Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 8 cores

Servers Status
  Apache Webserver (/apache/)
  PHP-FPM 8.3.11 Server
  BIND DNS Server (/bind8/)
  Postx Mail Server (/postx/)
  Dovecot IMAP / POP3 Server (/dovecot/)
  Cyrus SASL Authentication Server
  ProFTPD FTP Server (/proftpd/)
  ClamAV Virus Scanning Server
  SpamAssassin Filter Server
  MariaDB Database Server (/mysql/)

**Comment by iliajie** [comment]
> This system would be a great B system to support.

Okay, since we already have the facility to support Grade B/unstable versions, it’s straightforward to add support for Ubuntu interim (non-LTS) versions.

We already warn users that it’s not recommended, but it might be fine for someone who’s just testing.

Thanks for the heads up!
