### ISSUE TITLE
Centos 7.5 Digital Ocean Droplet

### ISSUE THREAD

**Issue by warhansen** [virtualmin/virtualmin-install#15]
When I install I get the following errors:

[root@web01 ~]# ./install.sh 

> chmod: cannot access ‘slib.sh’: No such file or directory
> ./install.sh: line 288: ./slib.sh: No such file or directory
> ./install.sh: line 291: serial_ok: command not found
>   Welcome to the Virtualmin GPL installer, version 6.0.11
>   This script must be run on a freshly installed supported OS. It does not
>   perform updates or upgrades (use your system package manager) or license
>   changes (use the "virtualmin change-license" command).
>   The systems currently supported by install.sh are:
>     CentOS/RHEL Linux 6 and 7 on x86_64
>     Debian 7, 8, and 9, on i386 and amd64
>     Ubuntu 14.04 LTS, 16.04 LTS, and 18.04 LTS, on i386 and amd64
>   If your OS/version/arch is not listed, installation will fail. More
>   details about the systems supported by the script can be found here:
>     https://www.virtualmin.com/os-support
>   The selected package bundle is LAMP and the size of install is
>   full. It will require up to 650 MB of disk space.
>   Exit and re-run this script with --help flag to see available options.
>  Continue? (y/n) ./install.sh: line 464: yesno: command not found
>

**Comment by swelljoe** [comment]
I believe this is the same as the other issue you filed. Downloads from one of our mirrors weren't working due to an expired certificate. Try it again.
