### ISSUE TITLE
Centos 7.5 Error

### ISSUE THREAD

**Issue by warhansen** [virtualmin/virtualmin-install#16]
I tested now on a default local install of Centos 7.5. I get this error:

> [INFO] Started installation log in /root/virtualmin-install.log
> 
> ▣□□ Phase 1 of 3: Setup
> Updating yum Groups                                                     [  ✔  ]
> Downloading virtualmin-release-latest.noarch.rpm                        [ERROR] Failed with error: 60
> [  ✘  ]
> 
> [ERROR] Something went wrong. Exiting.
> [ERROR] The last few log entries were:
> [2018-07-02 13:26:40 SAST] [DEBUG] Operating system name:    CentOS
> [2018-07-02 13:26:40 SAST] [DEBUG] Operating system version: 7.5.1804
> [2018-07-02 13:26:40 SAST] [DEBUG] Operating system type:    centos
> [2018-07-02 13:26:40 SAST] [DEBUG] Operating system major:   7
> [2018-07-02 13:26:40 SAST] [DEBUG] Configuring package manager for CentOS 7.5.1804...
> [2018-07-02 13:26:40 SAST] [DEBUG] Disabling SELinux during installation...
> [2018-07-02 13:26:40 SAST] [DEBUG]  setenforce 0 succeeded
> Spin pid is: 1522
> Made it here...why?
> Updating yum Groups: Success.
> Spin pid is: 1552
> Made it here...why?
> Downloading virtualmin-release-latest.noarch.rpm: [2018-07-02 13:26:42 SAST] [ERROR] Failed with error: 60
> [2018-07-02 13:26:42 SAST] [ERROR] Something went wrong. Exiting.
> [2018-07-02 13:26:42 SAST] [ERROR] The last few log entries were:
> [root@web-test ~]#

**Comment by swelljoe** [comment]
I'm guessing this was related to the certificate on one of our mirrors being expired for a few hours. Try it again.
