### ISSUE TITLE
Error: Systemd service fail2ban cannot be created unless a command is given

### ISSUE THREAD

**Issue by liamdemafelix** [virtualmin/virtualmin-install#19]
Installing Virtualmin GPL on a fresh Ubuntu 18.04.2 server exits with warnings after outputting the following error:

```
-----
Systemd service fail2ban cannot be created unless a command is given
-----
```

I assume that since this is a warning that the Virtualmin install went fine and this is just a warning of fail2ban being misconfigured and has nothing to do with everything else, or should I reinstall?

**Comment by swelljoe** [comment]
Yeah, that's not a catastrophic problem. I don't think I saw that in my testing, but 18.04 hasn't had as much recent testing as I'd like. I'm not even sure where that'd come from. We don't create a fail2ban service, I don't think, I think we use the one created by the fail2ban package, so it may be a problem at a lower level than the Virtualmin install. We just configure some fail2ban rules, and enable the service.

If you want to use fail2ban (recommended, if you have sufficient memory), you can go into Webmin->System->Bootup and Shutdown and make sure a fail2ban service exists and is set to start on boot.

Oh, actually...now that I'm thinking of it, this may be related to the selection of which firewall to use, which would be a virtualmin-config issue. I'll do some testing as soon as I get a few minutes to spare.

**Comment by swelljoe** [comment]
This is resolved in current installs (everybody is on firewalld, now, so no risk of mismatch).
