### ISSUE TITLE
Virtualmin source code

### ISSUE THREAD

**Issue by mikefedyk** [virtualmin/virtualmin-install#2]
I am having trouble finding the virtualmin source repo.  There are a couple issues against the webmin repo for this one and two years ago.  Has it been published anywhere?

**Comment by andreychek** [comment]
While it's possible to download the source code for Virtualmin from the Virtualmin software repository, there isn't actually a github repository containing all the code... sorry!

**Comment by swelljoe** [comment]
As soon as I get some free time, I'll be making all of the Virtualmin plugins public in their own repos. Making Virtualmin itself public will probably be a few months down the road, still, as we need to factor out the Pro code into its own modules.

But, in the meantime, the source is, of course, available in the tarball (and RPM and deb) and we accept patches against that. I know it's not ideal, but we're a small team, and lately I'm not able to devote much time to development issues.

**Comment by swelljoe** [comment]
I've started rolling out the modules into their own repos this weekend. As mentioned, Virtualmin (and Cloudmin) itself will take a while to re-factor into something we can put into a public repo (they currently share a directory with the Pro versions and it's non-trivial to split them out), but it's coming, too.

You can see the first few plugins showing up at the following links:

https://github.com/virtualmin/php-pear

https://github.com/virtualmin/ruby-gems

https://github.com/virtualmin/virtualmin-awstats

https://github.com/virtualmin/virtualmin-dav

With all of the rest of them coming over the next few days (it takes a couple hours per repo to split it out).

**Comment by mikefedyk** [comment]
Awesome!  Thank you!

**Comment by swelljoe** [comment]
Just a quick update on this: Jamie has been working on bifurcating the Pro from GPL code for a while now, and I think he's almost finished, so Virtualmin itself will be opened up in the next few...days, maybe? Maybe weeks. Hard to say, as it's a lot of work, and Jamie has his hands full, but it's definitely coming!

**Comment by jcameron** [comment]
Definitely a few more days at most.

**Comment by swelljoe** [comment]
And, it's done! All hail Jamie! (I realized just how much work it was while going over the history to make sure everything got pushed into the right repos.)

https://github.com/virtualmin/virtualmin-gpl

So, I'm pretty sure all of our OSS Virtualmin modules are now in public git repositories. Cloudmin will come eventually, but we gotta get Virtualmin 6 out the door before worrying about that. There's a few parts of the Virtualmin installer that are not yet in public repos, but that's coming over the next few days, as well, as I rebuild them for VM6.
