### ISSUE TITLE
Ubuntu 18.04 - DNS queries stop to work after Virtualmin installation

### ISSUE THREAD

**Issue by paulocoghi** [virtualmin/virtualmin-install#22]
After installing Virtualmin on an Ubuntu 18.04 server with a working network and dns, the dns queries don't work anymore after installing Virtualmin.

My workaround was to define the dns IP again through OpenVZ, externally to the server, and restart it.

Independently of my workaround and virtualization stack, the issue seems to be on the final configuration made by Virtualmin on its final steps of installation process, since dns queries work normally before the installation.

**Comment by paulocoghi** [comment]
This issue continues to happen on:

Webmin: **1.900**
Virtualmin: **6.06.gpl-2**
OS: **Ubuntu 18.04.2**

**Comment by RemyyB** [comment]
I have the same issue, when installing at 'net' it says no ethernet devices found, when installing ifupdown (as said on multiple forums) I sometimes get this error, I think it's a netplan issue, the 01-netplan yaml file seems to be misconfigured.

Standard it uses 2 spaces a.f.a.i.k but virtualmin changes it and half of the config is in 4 spaces that causes an error when trying netplan apply -d

**Comment by iliarostovtsev** [comment]
Hi,

We believe this issue has been fixed on Webmin 1.942.

You can safely install it from [devel repo](http://download.webmin.com/devel).

**Comment by RemyyB** [comment]
Ah I'm 1 version down, when will this release be on stable?

Thanks for your quick response btw :)

**Comment by iliarostovtsev** [comment]
It's in dev repo but it's not unstable. It's safe to try 1.942.

**Comment by RemyyB** [comment]
Thank you very much @iliarostovtsev, it works like a charm! You are my hero of the week

Since when is this version in beta? And why was this issue never fixed earlier? Because this post is from a year ago :/ Just curious :)

**Comment by iliarostovtsev** [comment]
I am glad I could help you. :slightly_smiling_face: 

> Since when is this version in beta? And why was this issue never fixed earlier? 

Sorry about that. We try our best to fix things, as soon as possible, it's just so much of everything to look over.

**Comment by RemyyB** [comment]
I understand, keep up the good work!

**Comment by swelljoe** [comment]
This is resolved in Virtualmin 7 installer. We no longer modify DNS resolver settings during install.
