### ISSUE TITLE
Ubuntu 18.04 - Fail2ban not working because of missing 'filter.d/sshd-ddos'

### ISSUE THREAD

**Issue by paulocoghi** [virtualmin/virtualmin-install#23]
After installing Virtualmin (LEMP stack) on Ubuntu 18.04, I realized that Fail2ban isn't working properly.

With a `service fail2ban status`, it shows a _failed_ state and the first message is

```
Found no accessible config files for 'filter.d/sshd-ddos'
```

And, indeed, this file doesn't exist on `/etc/fail2ban/filter.d`.

**Comment by jcameron** [comment]
Did you make any changes to the fail2ban config in Webmin, or did it failed to start immediately after an install?

**Comment by swelljoe** [comment]
It's our doing, I think (https://github.com/virtualmin/Virtualmin-Config/blob/dc93612ce426e077ebfa3ddb43e66c51d0cc4c3f/lib/Virtualmin/Config/Plugin/Fail2banFirewalld.pm#L96), I just assumed that filter would be available across all of our platforms.

I'll have to look into what we need to do to sort that out. Maybe it needs to be excluded on Debian/Ubuntu or maybe I just need to ensure that filter exists (it's a useful one, I think).

**Comment by paulocoghi** [comment]
> Did you make any changes to the fail2ban config in Webmin, or did it failed to start immediately after an install?

@jcameron , it failed to start immediately after the install

**Comment by paulocoghi** [comment]
@jcameron , I believe the best solution is to create it if not present on the install phase. If you have a good sample of it to use, IMHO, it's a good option.

**Comment by swelljoe** [comment]
No need to tag Jamie on this issue; I maintain Virtualmin-Config which is where this problem exists.

**Comment by swelljoe** [comment]
That filter has been removed upstream, and it seems to be included in the sshd filter, so I'm going to remove it from the default config. It won't affect existing installations, so you'll need to manually remove that section from `jail.local`.

It'll be fixed in the next Virtualmin-Config release.

**Comment by paulocoghi** [comment]
> No need to tag Jamie on this issue

Sorry. On my second message, I wish I had mentioned you, but I ended up wrongly mentioning Jamie. :grin:
