### ISSUE TITLE
Webmin not up-to-date in installer

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-install#24]
Using
```
wget http://software.virtualmin.com/gpl/scripts/install.sh
sh install.sh
```
to install virtualmin (and webmin) installs webmin version 1.900 instead of the currently released version 1.920

![Screen Shot 2019-07-11 at 10 47 21](https://user-images.githubusercontent.com/45786226/61036389-4ef5db00-a3c9-11e9-883e-9769e3f5e04d.png)

**Comment by rostovtsev** [comment]
Thank you for letting us know. We had technical reasons to postpone adding latest Webmin version to Virtualmin repos. 

It will be solved in the near future.

Thanks for reporting.

**Comment by PitWenkin** [comment]
Seems fixed
