### ISSUE TITLE
Post-install command prompt mispositioned

### ISSUE THREAD

**Issue by iliarostovtsev** [virtualmin/virtualmin-install#27]
After running install script and when it's finished with success, the command line prompt is shifted way to the right. Looks like the small and easy bug to fix.

Example:
```Bash
[21/23] Configuring Fail2banFirewalld                                   [  ✔  ]
[22/23] Configuring Postfix                                             [  ✔  ]
[23/23] Configuring Virtualmin                                          [  ✔  ]
▣▣▣ Cleaning up

[SUCCESS] Installation Complete!
[SUCCESS] If there were no errors above, Virtualmin should be ready
[SUCCESS] to configure at https://debug-ubuntu18.local:10000 (or https://192.168.122.251:10000).
[SUCCESS] You'll receive a security warning in your browser on your first visit.
                                                                        root@user:~/Downloads# 
```

![image](https://user-images.githubusercontent.com/4426533/62124446-e5cffc00-b2d2-11e9-8001-146f76e5332e.png)

**Comment by iliarostovtsev** [comment]
Okay, giving it more tests, I think I have [finally fixed](https://github.com/virtualmin/slib/commit/a25e9590322aa6dfe3d8866695ac5310d6a6a0d9) an issue and made all output look nice but most importantly readable:

**Successful output on repo setup:**
![image](https://user-images.githubusercontent.com/4426533/85867931-4d881300-b7d2-11ea-9bcb-c9d9b47f9583.png)

**Error output on repo setup:**
![image](https://user-images.githubusercontent.com/4426533/85868021-68f31e00-b7d2-11ea-8f9a-6b331f151340.png)

**Successful output on install:**
![image](https://user-images.githubusercontent.com/4426533/85868731-5b8a6380-b7d3-11ea-9732-61a88f9b700f.png)

**Error output on install (most importantly - readable):**

![image](https://user-images.githubusercontent.com/4426533/85868887-8ffe1f80-b7d3-11ea-8ab6-8af542f75bcf.png)

**Comment by swelljoe** [comment]
Incredible. I'd given up!
