### ISSUE TITLE
SSL on https://example.com:10000

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [virtualmin/virtualmin-install#29]
How to install SSL on https://example.com:10000

**Comment by rostovtsev** [comment]
Please Google this exact question.

**Comment by ParveenBhadooOfficial** [comment]
I found details to install SSL on domains in Virtual server. But i couldn't able to install ssl on the 10000 port of the Server Admin.

**Comment by rostovtsev** [comment]
Do you have **example.com**  added as virtual server in Virtualmin?

**Comment by ParveenBhadooOfficial** [comment]
I tried that too. But if i do. Ssl on example.com works while example.com:10000 still shows error.

**Comment by rostovtsev** [comment]
Then just go to SSL Certificate page and click **Copy to Webmin** button:

![image](https://user-images.githubusercontent.com/4426533/75228639-74512100-57c1-11ea-828c-cbf3a3d7b997.png)
