### ISSUE TITLE
CentOS 8 - enabling PowerTools did not work

### ISSUE THREAD

**Issue by HonkXL** [virtualmin/virtualmin-install#36]
I tried the script on a fresh install of CentOS 8 (I did a yum update first to make sure everything ist up-to-date).

Script started, but enabling PowerTools package failed:

```
▣▣□ Phase 2 of 3: Installation
Installing EPEL release package                                         [ OK! ]
Enabling PowerTools package repository                                  [=>---]
[ERROR]
[ERROR] Something went wrong with the previous command. Exiting.

```

**Comment by HonkXL** [comment]
I looked to the log:

`Installing EPEL release package: Success.
Spin pid is: 1765
No such command: config-manager. Please use /bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(config-manager)'"
Enabling PowerTools package repository: Failed with error: 1
[2020-06-05 16:30:35 CEST] [ERROR] Something went wrong with the previous command. Exiting.
`

**Comment by iliarostovtsev** [comment]
Hi,

Thank you for reporting!

What CentOS 8 image is that? Have you deployed it manually by downloading from official website or your ISP did it for you? If latter, what ISP is this exactly?

What do you have on install log printed?

What version of *install.sh* script is that?

**Comment by HonkXL** [comment]
I am using a VPS at Webtropia.com -> they offer a CentOS 8 minimal image without a admin panel.
So I don't have a install.log of the OS installation :-(

But: I tried to install VirtualMin now after running this command:

`dnf install 'dnf-command(config-manager)'`

**Comment by selfuntitled** [comment]
Just a quick confirmation note, also centos 8, I'm seeing the same issue with the latest Proxmox Centos template.  The above dnf fix also worked.

**Comment by iliarostovtsev** [comment]
This is frustrating that **dnf** core plugin **config-manager** might be missing like that. Preposterous!!

There is a [patch](https://github.com/virtualmin/virtualmin-install/commit/e2d1f712ef3771f5a75e9cb6a02fc4d10a5790a6) to the install script to address lame builds.

You can work around this for older versions of install script by running priorly:

~~~
dnf install dnf-plugins-core
~~~
