### ISSUE TITLE
Installing issue on Ubuntu 20

### ISSUE THREAD

**Issue by eSlider** [virtualmin/virtualmin-install#38]
By the installation there is an error from Webalizer this tries to read configuration file from `/etc/webalizer.conf` but it's here:`/etc/webalizer/webalizer.conf`

Here is an workaround to fix it before installation script runs:
```bash
ln -sf  /etc/webalizer/webalizer.conf /etc/webalizer.conf 
``` 

In additional, script mades some DNS settings, which had broked DNS resolving.
To fix it add some DNS server by doing this:

```bash
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
```

**Comment by iliarostovtsev** [comment]
Hi,

This is the issue of older Webmin version. It's been fixed already with new Webmin 1.952.

**Comment by iliarostovtsev** [comment]
How did those broken DNS recordings looked like?

**Comment by eSlider** [comment]
> Hi,
> 
> This is the issue of older Webmin version. It's been fixed already with new Webmin 1.952.

As I tried the installation script this I got from git, at same day I create this issue, to install Virtualmin, not Webmin, the error was there.

**Comment by eSlider** [comment]
> How did those broken DNS recordings looked like?

DNS resolving was corrupted, no really plan why.
I tried, as example, to ping any host, without any success, before I add  external DNS in `resolv.conf`

**Comment by swelljoe** [comment]
Closing. Virtualmin 7 installs fine on Ubuntu 20.04, and no longer modifies resolver config.
