### ISSUE TITLE
The default PHP install is EOL 7.0.33-0ubuntu0.16.04.15

### ISSUE THREAD

**Issue by dmiquel** [virtualmin/virtualmin-install#41]
As of December 3rd, 2018, PHP 7.0 reached its end of life. Why isn't the installer using 7.4?

**Comment by iliarostovtsev** [comment]
Hi,

Ubuntu 16 itself is about to reach its EOL and not recommended as a choice for a new, clean install. We are about to remove Ubuntu 16 from Virtualmin installer pretty soon.

**Comment by swelljoe** [comment]
If you want new packages, use a new distribution. We install what the OS provides, and usually support additional PHP versions when available. But, we trust you to pick the Linux distribution that meets your needs in terms of available packages and versions.
