### ISSUE TITLE
Installer for Fedora

### ISSUE THREAD

**Issue by SteffanCline** [virtualmin/virtualmin-install#43]
Joe, can you please set up the repos for the current versions of Fedora?

**Comment by iliarostovtsev** [comment]
Great suggestion, Steffan!

Meanwhile, I could easily install Virtualmin GPL on Fedora 33 with the following easy steps (**_Note:_** packages provided by _yum-groups_ were missing `cronie` package, which is now [fixed](https://github.com/virtualmin/virtualmin-yum-groups/commit/756038e82c6c4151eb351fcbfe770d0946e6fd8b)):

1. Edit and add to `/etc/yum.repos.d/virtualmin.repo` the following:

~~~
[virtualmin]
name=RHEL/CentOS/Fedora $releasever - x86_64 - Virtualmin
baseurl=https://software.virtualmin.com/vm/6/gpl/centos/8/x86_64/
enabled=1
gpgcheck=1
gpgkey=https://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-6
       https://software.virtualmin.com/lib/RPM-GPG-KEY-webmin

[virtualmin-neutral]
name=RHEL/CentOS/Fedora $releasever - x86_64 - Virtualmin Neutral
baseurl=https://software.virtualmin.com/vm/6/gpl/universal/
enabled=1
gpgcheck=1
gpgkey=https://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-6
       https://software.virtualmin.com/lib/RPM-GPG-KEY-webmin
~~~

2. Install manually `jailkit` package:

~~~
cd /tmp
wget https://software.virtualmin.com/vm/6/gpl/fedora/32/x86_64/jailkit-2.21-1.fc32.vm.x86_64.rpm
dnf install jailkit-2.21-1.fc32.vm.x86_64.rpm -y
rm -f jailkit-2.21-1.fc32.vm.x86_64.rpm
~~~

3. Install packages expected by LAMP bundle:

~~~
dnf install bind bind-utils ca-certificates httpd httpd-itk iptables mod_ssl openssl perl-Crypt-SSLeay perl-DBD-MySQL perl-JSON-PP perl-JSON-XS perl-Log-Log4perl perl-LWP-Protocol-https perl-Module-Load perl-open perl-parent perl-Time-HiRes perl-XML-Simple perl-File-Basename perl-lib php-cli php-fpm php-gd php-imap php-mbstring php-pear python quota unzip zip perl-Authen-OATH awstats bzip2 certbot chrony clamav clamav-update clamd cyrus-sasl cyrus-sasl-gssapi cyrus-sasl-plain dovecot fail2ban-firewalld fail2ban-server firewalld logrotate mariadb mariadb-devel mariadb-server milter-greylist mod_fcgid opendkim p7zip perl-Config-IniFiles perl-IO-Tty php-json php-mysqlnd php-opcache php-xml php-xmlrpc postgrey procmail procmail-wrapper proftpd ruby ruby-devel rubygems spamassassin tar wbm-virtualmin-awstats webalizer xz perl-DBD-Pg php-odbc php-pgsql php-snmp postgresql postgresql-devel postgresql-server virtualmin-config wbm-virtualmin-htpasswd wbm-jailkit usermin cronie
~~~

4. Restart Webmin manually (just in case):

~~~
/etc/webmin/restart
~~~

5. Run config systems for LAMP bundle:

~~~
virtualmin-config-system -b LAMP
~~~

.. and it seems to work just fine:


![image](https://user-images.githubusercontent.com/4426533/106365570-79aada00-6347-11eb-961e-eb1cdc70c6d6.png)

**Comment by iliarostovtsev** [comment]
.. and it seems to work for wizard flawlessly too:

![image](https://user-images.githubusercontent.com/4426533/106365839-36516b00-6349-11eb-83e8-7c255df17bab.png)

**Comment by marclaporte** [comment]
So is Fedora a "Grade B" or "Others" here?
http://www.virtualmin.com/os-support/

Thanks!

**Comment by swelljoe** [comment]
Fedora is somewhere between A and B. But, I think the grades need a rethink/refactor to more strongly discourage using any OS but a Grade A supported OS. After all these years, it's exhausting answering questions from folks who installed manually (or think they did, but really did a half-assed or quarter-assed job of it and left dozens of steps undone) and then expect help without any understanding that they're working with a very incomplete installation.

**Comment by swelljoe** [comment]
This is no longer relevant (RPM repos have merged into two repos that should work on all RPM-based distros with dnf), but I still don't recommend using Fedora for a server.
