### ISSUE TITLE
The Procmail program needed for spam filtering does not appear to be installed on your system, or has not yet been set up properly in Webmin's Procmail Mail Filter module. If your system does not use spam filtering, it should be disabled in Virtualmin's module configuration page.

### ISSUE THREAD

**Issue by yashlikhar** [virtualmin/virtualmin-install#44]
i have freshly installed virtualmin on ubuntu 20.4 and this problem shows when i recheck and refresh configuration_

The Procmail program needed for spam filtering does not appear to be installed on your system, or has not yet been set up properly in Webmin's Procmail Mail Filter module. If your system does not use spam filtering, it should be disabled in Virtualmin's module configuration page.

**Comment by swelljoe** [comment]
Are you on some architecture other than x86_64/i386?

**Comment by yashlikhar** [comment]
yess i am using Arm64

**Comment by yashlikhar** [comment]
> Are you on some architecture other than x86_64/i386?

yes i am using arm64

**Comment by swelljoe** [comment]
https://www.virtualmin.com/os-support

**Comment by swelljoe** [comment]
Feel free to ask questions on the forums if you still want to try to set it up manually. There have already been several discussions about Arm, so please search and get up to speed on the state of things first.

**Comment by yashlikhar** [comment]
> Feel free to ask questions on the forums if you still want to try to set it up manually. There have already been several discussions about Arm, so please search and get up to speed on the state of things first.

all other services are running properly, i am getting issue on mail server, isn't there any other way to run mail server get running

**Comment by swelljoe** [comment]
https://forum.virtualmin.com/t/the-procmail-command-in-the-postfix-configuration-does-not-exist/109782

**Comment by yashlikhar** [comment]
> https://forum.virtualmin.com/t/the-procmail-command-in-the-postfix-configuration-does-not-exist/109782

i think i will  use different system for mail server that way i can run mail services running, 
coz on that raspberrypi other all services are working absolute fine.
whats your pov on this??

**Comment by yashlikhar** [comment]
> https://forum.virtualmin.com/t/the-procmail-command-in-the-postfix-configuration-does-not-exist/109782

hey hey listen i just solved that error...... yayyy 

but another error came 

The procmail command /bin/procmail is owned by group mail, when it should be owned by root. Email may not be properly delivered or checked for spam

you know how to solve this??

**Comment by swelljoe** [comment]
> Feel free to ask questions on the forums if you still want to try to set it up manually. There have already been several discussions about Arm, so please search and get up to speed on the state of things first.
