### ISSUE TITLE
mail problem

### ISSUE THREAD

**Issue by yashlikhar** [virtualmin/virtualmin-install#46]
This is the mail system at host mail.mine8.in.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<yashlikhar13@gmail.com>: host gmail-smtp-in.l.google.com[74.125.24.26] said:
    550-5.7.26 This message does not have authentication information or fails
    to 550-5.7.26 pass authentication checks. To best protect our users from
    spam, the 550-5.7.26 message has been blocked. Please visit 550-5.7.26
    https://support.google.com/mail/answer/81126#authentication for more 550
    5.7.26 information. t17si19162202pgh.400 - gsmtp (in reply to end of DATA
    command)

how to solve this

**Comment by jcameron** [comment]
Make sure you have your DKIM and SPF records setup correctly

**Comment by swelljoe** [comment]
We'd need to see relevant maillog entries to really try to solve this (and this is best discussed in the forum, as well, since it's not an installer issue).
