### ISSUE TITLE
Rocky Linux support

### ISSUE THREAD

**Issue by hbjydev** [virtualmin/virtualmin-install#49]
Hi all!

Now that Rocky Linux is released, I'd love to work with you on getting this project functional on Rocky Linux 8.3! Let me know what needs to be done and I'll do what I can! :)

**Comment by jcameron** [comment]
Is Rocky Linux based on some other more common distro, like RHEL?

**Comment by hbjydev** [comment]
Yep! It's built from the same sources as RHEL is, and it's aiming to be bug-for-bug compatible. Think of it as CentOS, but not being replaced by Stream.

**Comment by jcameron** [comment]
Do the versions line up? Like is Rocky 8.3 the same as RHEL 8.3 ?

**Comment by hbjydev** [comment]
Yep.

**Comment by jcameron** [comment]
Thanks - the next Webmin release will better support Rocky Linux. Work still needs to be done on the Virtualmin installer though.

**Comment by hbjydev** [comment]
What work needs doing on the Virtualmin installer?

**Comment by hbjydev** [comment]
I've started working on a fork that installs properly, and it does, until you go to configure it in the browser.

![image](https://user-images.githubusercontent.com/22327045/116813497-ec487300-ab4b-11eb-9872-20539e58c45c.png)

I assume this is because Virtualmin itself doesn't know how to work with Rocky?

**Comment by swelljoe** [comment]
No. That is Webmin treating the OS as a generic OS.

**Comment by hbjydev** [comment]
Right. Is there somewhere I would need to go in Webmin to patch that? Code-wise, I mean

**Comment by iliarostovtsev** [comment]
Jamie, I have installed Rocky Linux and Virtualmin on it using patched `install.sh` script and things seem to work pretty smooth.

This is what Webmin thinks of it:

![image](https://user-images.githubusercontent.com/4426533/117002118-cfe33c80-aceb-11eb-9083-d742ddaeaec7.png)

However, MariaDB Server is not detected correctly by default.

Here is the example of working config (manually adjusted):

~~~
mysql=/usr/bin/mysql
nodbi=0
my_cnf=/etc/my.cnf.d/mariadb-server.cnf
date_subs=0
passwd_mode=0
mysqladmin=/usr/bin/mysqladmin
mysqlimport=/usr/bin/mysqlimport
stop_cmd=systemctl stop mariadb
max_text=1000
webmin_subs=0
mysql_libs=
nopwd=0
access=*: *
mysqldump=/usr/bin/mysqldump
max_dbs=50
style=1
blob_mode=0
mysql_data=/var/lib/mysql
perpage=25
start_cmd=systemctl start mariadb
mysqlshow=/usr/bin/mysqlshow
add_mode=1
port=
host=
sock=
mysqld=
~~~

It was set initially to `/etc/my.cnf` and start and stop commands were set to use `/etc/rc.d`.

**Comment by iliarostovtsev** [comment]
> Right. Is there somewhere I would need to go in Webmin to patch that? Code-wise, I mean

You can use config above by placing it to `/etc/webmin/mysql/config` file.
