### ISSUE TITLE
install.sh fails on RedHat 8 with repo error at software.virtualmin.com

### ISSUE THREAD

**Issue by verne-wv** [virtualmin/virtualmin-install#52]
as I wrote in the forums today ....

have been running VirtualMin on RHEL5 and 6 and 7 very well … GREAT PACKAGE

Today is my first attempt to install it on RHEL8, and I am getting what I thought was a very simple error, but not sure how to fix it.

multiple install scripts and

`yum install wbm-virtual-server-6.16.gpl-1.noarch.rpm
`

all want to access the URL

`http://GPL:GPL@software.virtualmin.com/gpl/rhel/8/x86_64/`

which does not exist ... there is no "8" tree ... only 7 or 7Server.

Should I make my own REPO file and point it at the 7Server tree? I even pulled the script from

`https://raw.githubusercontent.com/virtualmin/virtualmin-install/master/virtualmin-install.sh`

and still get the same error.

I was really REALLY hoping to finish this tonight (its almost 5pm EDT) …

my fallback position is to go with my tried and true RHEL7 setup, mostly driven by puppet with lots of local custom automation (but it works).

Thoughts anyone?

Verne

**Comment by verne-wv** [comment]
I see Ilia mentions in another open issue to try

`https://software.virtualmin.com/vm/6/gpl/centos/8/x86_64/`

inside a custom REPO file ... but in browsing that just now, its way out of date.   OR --- I should try the "latest" placeholder and see what it gives me ..........

**Comment by swelljoe** [comment]
You're using an *ancient* version of the install.sh, or you're not using the install.sh. Either of those is a bad idea.

**Comment by swelljoe** [comment]
The correct repo URLs are inside of the /vm/6 subdirectory, and the install.sh will set them up for you.

**Comment by swelljoe** [comment]
There is not and will never be support for RHEL 8 or CentOS 8 in the old Virtualmin 5 (and below) repos.

**Comment by verne-wv** [comment]
if I can re-trace my steps tomorrow at webmin.com and virtualmin.com, I will let you know where the out-of-date installers are linked.

so ... where do I find a better install.sh ..... I really did try to look around today .... one I tried (I am at home right now) I think was installer 6.2.2

also at https://software.virtualmin.com/vm/6/gpl/centos/8/x86_64 all I see is VM 6.0.3 that is over one year old  :-) 


Verne

**Comment by swelljoe** [comment]
The Download page at Virtualmin.com is all there is. Everyone wanting to install Virtualmin should start at Virtualmin.com. The download page will link you to `install.sh`, and you don't need to poke around in random repo directories trying to figure out what to do with them. 

> so ... where do I find a better install.sh ..... I really did try to look around today .... one I tried (I am at home right now) I think was installer 6.2.2

6.2.2 is the current version. But, this ticket can't possibly be related to installing with install.sh version 6.2.2. As it refers to repositories that haven't been used by install.sh in 3+ years. I don't know how you got to the state you're in, but it wasn't install.sh 6.2.2 that got you there.

> also at https://software.virtualmin.com/vm/6/gpl/centos/8/x86_64 all I see is VM 6.0.3 that is over one year old :-)

That's not Virtualmin. Virtualmin is not in that repo, at all. A `release` package sets up repositories for yum/dnf. It contains no software at all, and you wouldn't need to install it manually; install.sh does it for you.

You're really making this much harder than it should be, and guaranteeing you get a broken installation. Just go to Virtualmin.com and click Download, follow the instructions. Installation on RHEL is less well-tested and lacks some of the polish of CentOS 8, but nothing like what you've reported (again, you had to have run a three+ year old version of the install.sh to get to the problem you're reporting, which is obviously something you should not expect to work).

**Comment by swelljoe** [comment]
And, the devel version of the install script is intended for developers. It literally can't work without modifications as there is no /vm/7 repo.

When you run the following:

`/bin/sh install.sh --setup`

On a freshly installed RHEL 8, what appears in `/etc/yum.repos/virtualmin.repo`?

**Comment by verne-wv** [comment]
as always, YOU ARE RIGHT !!!   I had an older repo file for virtualmin that I did not realize was on my system.  Once I removed that file and let install.sh "do its thing", all was good !!

Sorry for not paying more attention ... maybe I'm getting too old for this stuff   :-)

Verne
