### ISSUE TITLE
install_with_yum() in virtualmin-install.sh while installing on RHEL 7.9

### ISSUE THREAD

**Issue by zeshanb** [virtualmin/virtualmin-install#53]
While trying to install Virtualmin on RHEL 7.9 the install script was keep freezing on lines 838 to 856 during the final steps of the installation. I had no choice but to comment out lines 838 to 856.

`install_with_yum () {
  # RHEL 8 specific setup
  #if [ "$os_major_version" -ge 8 ] && [ "$os_type" = "rhel" ]; then
    # Important Perl packages are now hidden in CodeReady repo
  #  run_ok "$install_config_manager --set-enabled codeready-builder-for-rhel-$os_major_version-x86_64-rpms" "Enabling Red Hat CodeReady package repository"
  #  run_ok "$install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$os_major_version.noarch.rpm" "Installing EPEL $os_major_version release package"
  # RHEL 7 specific setup
  #if [ "$os_type" = "rhel" ]; then
    #run_ok "$install https://dl.fedoraproject.org/pub/epel/epel-release-7-13.noarch.rpm" "Installing EPEL 7 release package"
  # install extras from EPEL and SCL
  #elif [ "$os_type" = "centos" ]; then
    #install_epel_release
    #if [ "$os_major_version" -lt 8 ]; then
      # No SCL on CentOS 8
     # install_scl_php
    #fi
  #fi`

The best recourse when issues are encountered while using the install script while trying to install on RHEL is the following:

- Download the install script `wget http://software.virtualmin.com/gpl/scripts/install.sh`
- Provide execute privilege `chmod +x install.sh`
- Run the install script `./install.sh`
- install epel repo `yum install https://d1.fedoraproject.org/pub/epel-release-7.noarch.rpm`
- On your RHEL dev subscription run this command `subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms" --enable "rhel-ha-for-rhel-*-server-rpms"`
- notice install scroll text - fedoraproject rpm "skipping"
- follow on terminal text to skip repos if not available
- When install script stops due to a issue, uninstall using `./install.sh --uninstall` before running install.sh again.
-
Here is the install-sh.txt I used. I've renamed .sh to .txt.
[install-sh.txt](https://github.com/virtualmin/virtualmin-install/files/6951126/install-sh.txt)

**Comment by swelljoe** [comment]
I'm going to close this, as we've since released Virtualmin 7, and I believe it has been tested and is known to work on current versions of RHEL.
