### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by kah0922** [virtualmin/virtualmin-install#54]
As of Debian 11/Ubuntu 21.04, apt-key is depreciated, with the recommended method of adding gpg keys listed here: [https://wiki.debian.org/DebianRepository/UseThirdParty](https://wiki.debian.org/DebianRepository/UseThirdParty)

[Debian 11 and Ubuntu 22.04 will be the final releases to include apt-key](https://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html).

The simplest way of doing this would be to replace apt-key with the following commands
`curl https://software.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-6 | gpg --dearmor > /etc/apt/trusted.gpg.d/RPM-GPG-KEY-virtualmin-6.gpg`
`curl https://software.virtualmin.com/lib/RPM-GPG-KEY-webmin | gpg --dearmor > /etc/apt/trusted.gpg.d/RPM-GPG-KEY-webmin.gpg`

This method also works on Debian 10/Ubuntu 20.04 LTS.

**Comment by swelljoe** [comment]
Fixed in the Virtualmin install script.
