### ISSUE TITLE
Installation fails because of fail2ban

### ISSUE THREAD

**Issue by unsalkorkmaz** [virtualmin/virtualmin-install#56]
Hi,
I installed ubuntu on windows 11 wsl2 system with gui. Then tried to install virtualmin but got error because of fail2ban.
[virtualmin-install.log](https://github.com/virtualmin/virtualmin-install/files/8473637/virtualmin-install.log)

Any suggestions?

![Untitled](https://user-images.githubusercontent.com/207720/162979550-caf25094-5786-477d-9453-a509c4dbb59c.png)

**Comment by iliajie** [comment]
Have you ran `apt-get update && apt-get upgrade` before installing Virtualmin?

**Comment by unsalkorkmaz** [comment]
this is the result of trying to purge:
![Screenshot 2022-04-12 175158](https://user-images.githubusercontent.com/207720/162990696-5bd9df8c-3b1f-4fa2-831e-f66576e9a68f.png)

**Comment by iliajie** [comment]
This seems as a general system error and must be sorted out before Virtualmin can be installed.

There is not much we can do here.

**Comment by swelljoe** [comment]
We've never tested on WSL. It's not a high priority, as nobody would run that on a server.

**Comment by unsalkorkmaz** [comment]
I recommend using bridge connection:
https://github.com/microsoft/WSL/issues/4150#issuecomment-1018524753

**Comment by unsalkorkmaz** [comment]
You can install mkcert for local SSL certification:
https://chocolatey.org/install#individual
`choco install mkcert`
https://github.com/FiloSottile/mkcert

**Comment by unsalkorkmaz** [comment]
Not sure why, but virtualmin doesnt start automatically;
`/etc/init.d/webmin start`
![Screenshot 2022-04-12 222725](https://user-images.githubusercontent.com/207720/163038920-cd16e8b5-69e2-4e67-a9fc-7d5f41340342.png)

**Comment by iliajie** [comment]
> Not sure why, but virtualmin doesnt start automatically;
> `/etc/init.d/webmin start`

We have a fix for this in upcoming Webmin 1.991.

**Comment by unsalkorkmaz** [comment]
https://docs.microsoft.com/en-us/windows/wsl/wsl-config
https://www.srccodes.com/change-hostname-ubuntu-microsoft-windows-subsystem-for-linux-wsl-wsl2-wsl-conf-unable-resolve-hosts-name-service-not-known-list-running-shutdown-vm-srccodes/

`sudo nano /etc/wsl.conf`

```
[network]
hostname = korkmaz.local.dev
generateHosts = false

# Set a command to run when a new WSL instance launches. 
[boot]
command = /etc/init.d/webmin start

```

**Comment by unsalkorkmaz** [comment]
Current problem is, none of services starts automatically in start:
![Screenshot 2022-04-12 225508](https://user-images.githubusercontent.com/207720/163043049-93425feb-a213-4aba-95cc-add6f237f098.png)

**Comment by unsalkorkmaz** [comment]
For automatically start the services;
System Settings -> Virtualmin Configuration -> Status collection -> Restart services that are detected as down -> YES

`sudo nano /etc/wsl.conf`
find:
`command = /etc/init.d/webmin start`
replace:
`command = /etc/init.d/webmin start && sudo /etc/webmin/status/monitor.pl`

**Comment by unsalkorkmaz** [comment]
ssh service doesnt start;
https://www.garron.me/en/linux/sshd-no-hostkeys-available-exiting.html

`sudo ssh-keygen -A`

**Comment by iliajie** [comment]
None of this is Virtualmin installer issue.

**Comment by unsalkorkmaz** [comment]
> None of this is Virtualmin installer issue.

Yeah. Sorry, trying to collect info for people who needs in future. Should I stop it here?

**Comment by unsalkorkmaz** [comment]
```
sudo apt remove openssh-server
sudo apt install openssh-server
```

Webmin -> Servers -> SSH Server -> Authentication -> Allow authentication by password? -> YES
