### ISSUE TITLE
Problem on Debian11 minimal 

### ISSUE THREAD

**Issue by unsalkorkmaz** [virtualmin/virtualmin-install#59]
[virtualmin-install.log](https://github.com/virtualmin/virtualmin-install/files/8609586/virtualmin-install.log)

**Comment by iliajie** [comment]
Thanks for the heads up. We are aware. Although, we haven't announced official support for Debian 11 and Ubuntu 22.04, so it's not a problem, as Joe is still working on adding support for it.

We will announce it soon.
