### ISSUE TITLE
Dumb question: Should procmail-wrapper.c be modernized?

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#60]
1. Why couldn't this tiny, 20 lines of code, one function, simple `procmail-wrapper.c` program be ported from C to something cross platform and universally compatible with all CPU architectures such as a bash shell script, so that it could finally run on ARM and ARM64 and escape from a seemingly unnecessary requirement of binary compatibility to X86/X86-64?
2. Or, why isn't it getting compiled from source on the server at install time, so that, again, it could run on any arch including ARM/ARM64 ?

**Comment by swelljoe** [comment]
It can run on ARM. It compiles with one command, takes thirty seconds. The issue with ARM support is I simply don't have time right now to maintain yet another distro/architecture combination. It's already dozens of repositories.

We are deprecating procmail in Virtualmin 8 (which is, admittedly, a long way off).

**Comment by chris001** [comment]
OK so this is actually a devops issue, caused by linux distro forking.  How to reduce test workload burden on humans and shift it over to automated Travis test scripts here on github, for the purpose of validating that install script successfully runs to the end, with zero error codes, on all distros.  This is painless and easy to setup, it's been done by many projects before already, and should be prioritized, because it'd positively impact the entire dev test and release cycle by getting to play on easy mode.

**Comment by swelljoe** [comment]
Are you volunteering to write those tests?

**Comment by chris001** [comment]
I'd be game to look into how to get Travis to auto run the test install on each and every OS.

**Comment by swelljoe** [comment]
Travis is broken, and will need human intervention from the Travis CI folks. When I turned Virtualmin into an organization if broke the Travis connection and I was unable to get it back.

**Comment by swelljoe** [comment]
Note that the existing tests just validate code, they do not run the install script. Running tests here does not test an install, it confirms the code passes some code quality checks.

**Comment by chris001** [comment]
> Travis is broken, and will need human intervention from the Travis CI folks, as far as I know. When I turned Virtualmin into an organization it broke the Travis connection and I was unable to get it back.

[Contact Travis Support](https://app.travis-ci.com/help?anchor=top&page=https%3A%2F%2Fapp.travis-ci.com%2Fgithub%2Fvirtualmin) because you're a maintainer/member of the Virtualmin github organization.

**Comment by chris001** [comment]
> Note that the existing tests just validate code, they do not run the install script. Running tests here does not test an install, it confirms the code passes some code quality checks.

Thanks, the PR #61 I made still does that `prove`, and also creates several OS containers, downloads and runs the install script inside them.

**Comment by jcameron** [comment]
We *could* actually compile the procmail-wrapper.c file at Virtualmin install time as an alternative to supplying a binary package, in theory..

**Comment by chris001** [comment]
> We _could_ actually compile the procmail-wrapper.c file at Virtualmin install time as an alternative to supplying a binary package, in theory..

Or, rewrite it in bash shell script so that no compilation would be required?  Any tech reason not to?  It simply checks arguments, and calls `setguid` `setuid` and `exec`.

**Comment by swelljoe** [comment]
Production servers shouldn't have compilers. :man_shrugging:

**Comment by iliajie** [comment]
Besides, this is not the only one package we need to support ARM.

**Comment by chris001** [comment]
@swelljoe @iliajie 
I wrote to Travis support and received a reply, they say to do this to reconnect the virtualmin org and its repos to Travis:
"...please sign into your personal user account (on https://www.travis-ci.com ) and then add your missing org (virutalmin) from your profile page, or by following the link:

https://github.com/apps/travis-ci/installations/new
"
Reminder, it's free for open source projects such as this!

**Comment by swelljoe** [comment]
Travis CI continues to be broken for Virtualmin repos. I tried multiple times to go through the "activate" and add repos steps and it continues to say "We couldn’t find any active repositories you have access to. You can add repositories by clicking the “Manage repositories on GitHub” button above."

No errors, the repos just never show up. I'm done fighting with Travis again for a while.

**Comment by chris001** [comment]
Seems to be an access rights issue.  Travis (the website) has to be able to "see" that you're an officially listed "member" of this virtualmin github "organization".  I browsed this girhub "organization" and see no names listed.  Whoever is the official "owner" of this github organization, needs to click and add you as a "member", and/or manager of this repo, whatever is the high enough access rights to do the adding Travis to this repo here on github and adding the repo to Travis on travis-ci.com also.

**Comment by swelljoe** [comment]
I am the owner of the organization, and I have done that. It simply does not work.

**Comment by swelljoe** [comment]
This was a problem way back when I converted it to an org. It continues to be a problem. Apparently if they had it setup with user access and then it gets converted to an organization, something just breaks, and there's nothing to be done about it. I don't know.

**Comment by chris001** [comment]
That issue had to do with the travis "org to com migration" and was [happening back in October](https://travis-ci.community/t/org-to-com-migration-no-repositories-found/12249) however I believe they've gotten it fully under control.  If you'd [contact Support](https://app.travis-ci.com/help?anchor=top&page=https%3A%2F%2Fapp.travis-ci.com%2Fgithub%2Fvirtualmin) and [paste in your above comment](https://github.com/virtualmin/virtualmin-install/issues/60#issuecomment-1120292676), and the support rep will troubleshoot and guide you right thru the process until successful activation.

**Comment by chris001** [comment]
@swelljoe When I hover the mouse over your username/pic here on github, the popup doesn't say anything about "owner of repo" or "manager of organization", just says "committed to this repo". Maybe these ACL access rights to the org and repo, need to be set "visible" for Travis to see you have them, and therefore let you do access restricted things like activate the github Travis app onto all the virtualmin org's repos...?

**Comment by swelljoe** [comment]
It sees them, and it allows me to go through the process of adding access via Githubs Apps UI. It _looks_ like it is working (I've done this hundreds of times for a bunch of apps for my other work, this is not unfamiliar terrirory). It just doesn't show them when that's done (several times).

**Comment by chris001** [comment]
Let me share the full support message from Erika at Travis just so it'll make more sense:
"Hi Chris,
 
Thanks for your reply, it looks like from our database virtualmin is a user account, is this correct? If so, please sign into https://www.travis-ci.com/ from the user account "virtualmin". If this is an organizational account, please sign into your personal user account and then add your missing org from your profile page, or by following the link:

https://github.com/apps/travis-ci/installations/new

Best,

--
Erika

Your Friends @Travis CI

Test and Deploy with Confidence.
[www.travis-ci.com](http://www.travis-ci.com/)

—
Travis CI GmbH, Rigaer Str.8, 10247 Berlin, Germany | GF/CEO: Randy Jacops | Contact: [contact@travis-ci.org](https://espacenetworks.com:20000/mailbox/reply_mail.cgi?new=1&to=contact%40travis%2Dci%2Eorg) | Amtsgericht Charlottenburg, Berlin, HRB 140133 B | Umsatzsteuer-ID gemäß §27 a Umsatzsteuergesetz: DE282002648"

Looks like, the problem is, their database thinks "virtualmin" is still a user account as it used to be, yet you converted it into an org account, so I think you need to [contact support](https://app.travis-ci.com/help?anchor=top&page=https%3A%2F%2Fapp.travis-ci.com%2Fgithub%2Fvirtualmin) and tell them this, so maybe then they'll convert it to an org account on their side database?
