### ISSUE TITLE
Procmail doesn't get configured for use by SpamAssassin.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#62]
Steps to reproduce, Installed webmin and the 7.0 deb downloaded from webmin site to ubuntu 22.04, clean install no errors.
`System Settings` `Re-Check Configuration` says `SpamAssassin and Procmail are installed and configured for use` and `.. your system is ready for use by Virtualmin`
However, `Webmin Servers` `SpamAssassin Mail Filter` says:
```
Warning!  SpamAssassin does not appear to be set up in the system's Procmail configuration file /etc/procmailrc, so any configuration done using this module will have no effect unless users have it set up individually. 
```
Is this a bug? Shouldn't Webmin or Virtualmin auto configure `/etc/procmailrc` for use, when it notices the `procmailrc` settings are missing and SpamAssassin is active?

**Comment by iliajie** [comment]
Hello, Chris.

No, this is all and only configured when installed by [`install.sh`](https://www.virtualmin.com/download/) script with `virtualmin-config-system` command. You must _never_ install `.deb` or `.rpm` package from _webmin.com_ site. Always use official `install.sh` script!

Jamie, can we remove that from _webmin.com_  website and mention that Virtuamin must only be installed using `install.sh` script.

@swelljoe Joe, by the way, we could add a notice in config check, if Virtualmin wasn't installed using `install.sh` script,by creating some flag using `virtualmin-config-system` in config directory, which could be tested on config check. If the installation is new (7+) and the flag is missing, we must tell the user in a danger alert that Virtualmin must only be installed using `install.sh` script. That would help users not to be left with a broken installation.

**Comment by swelljoe** [comment]
No. That is absolutely not how you install Virtualmin. The documentation for installing Virtualmin is at https://www.virtualmin.com/download/

**Comment by chris001** [comment]
How to repair this `procmailrc` ?  
Is there a command line to install the proper content into that `/etc/procmailrc` file?  
Or, can one just copy the file from a different Virtualmin server, which is not complaining of that file lacking proper settings, that server was installed by shell command script on debian 10 OS and the OS upgraded afterward to debian 11?

**Comment by jcameron** [comment]
Yeah, you could just copy the file across.
