### ISSUE TITLE
Error on fresh Ubuntu install of 22.04

### ISSUE THREAD

**Issue by ioniks** [virtualmin/virtualmin-install#63]
Hi, 

when i test on VM the Virtualmin installer 7.0.0-RC5 on Fresh 22.04 Install with all update.

On Installing Virtualmin and all related packages     i have     [ERROR] Failed with error: 100

With detailed error : 
Les paquets suivants contiennent des dépendances non satisfaites :
 virtualmin-core : Depends: virtualmin-config mais il n'est pas installable
                   Recommends: webmin-jailkit mais il n'est pas installable
                   Recommends: webmin-php-pear mais il n'est pas installable
                   Recommends: webmin-ruby-gems mais il n'est pas installable
                   Recommends: webmin-virtualmin-awstats mais ne sera pas installé
                   Recommends: webmin-virtualmin-htpasswd mais ne sera pas installé
                   Recommends: liblog-log4perl-perl mais ne sera pas installé
E: Unable to correct problems, you have held broken packages.
Installing Virtualmin and all related packages: [2022-05-12 20:45:28 UTC] [ERROR] Failed with error: 100
[2022-05-12 20:45:28 UTC] [ERROR] Something went wrong. Exiting.
[2022-05-12 20:45:28 UTC] [ERROR] The last few log entries were:

If this Issue is not needed before the VM7 installer released, please ignore it and close it.

Thanks for your work.

**Comment by jcameron** [comment]
Can you switch your system to english and re-try the install? I'm not able to translate those error messages.

**Comment by ioniks** [comment]
Yes this is the error in english :

[ERROR] Something went wrong. Exiting.
[ERROR] The last few log entries were:
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 virtualmin-core : Depends: virtualmin-config but it is not installable
                   Recommends: webmin-jailkit but it is not installable
                   Recommends: webmin-php-pear but it is not installable
                   Recommends: webmin-ruby-gems but it is not installable
                   Recommends: webmin-virtualmin-awstats but it is not going to be installed
                   Recommends: webmin-virtualmin-htpasswd but it is not going to be installed
                   Recommends: liblog-log4perl-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Installing Virtualmin and all related packages: [2022-05-13 05:56:52 UTC] [ERROR] Failed with error: 100
[2022-05-13 05:56:52 UTC] [ERROR] Something went wrong. Exiting.
[2022-05-13 05:56:52 UTC] [ERROR] The last few log entries were:

**Comment by swelljoe** [comment]
It is not expected to work on Ubuntu, yet.

**Comment by swelljoe** [comment]
I will announce on the Virtualmin News forum when the repos are working and Ubuntu and Debian are expected to work.
