### ISSUE TITLE
php*-fpm

### ISSUE THREAD

**Issue by unsalkorkmaz** [virtualmin/virtualmin-install#67]
Can you change this if possible?
![Screenshot 2022-05-18 124951](https://user-images.githubusercontent.com/207720/169015068-ad0f4484-7141-4b47-b9e5-6203bb42253c.png)

![Screenshot 2022-05-18 130809](https://user-images.githubusercontent.com/207720/169015065-1dd3ece1-b104-47cb-8f67-e45e68adc701.png)

**Comment by iliajie** [comment]
Do you mean removing PHP and Apache?

**Comment by iliajie** [comment]
I given it a close look and it seems that your install script is outdated.

**Comment by unsalkorkmaz** [comment]
this is a fresh install on debian 10 minimal with this code:
```
cd /tmp && wget http://software.virtualmin.com/gpl/scripts/install.sh && chmod +x install.sh && ./install.sh --bundle LEMP
```

 how many php-fpm version gets installed is the problem

**Comment by iliajie** [comment]
This will be fixed for Virtualmin 7.
