### ISSUE TITLE
Still writes to /etc/resolv.conf , causes docker test build to fail.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#69]
Found another line in the install process (last one, looks like) trying to write to `/etc/resolv.conf` during the install.
Causes my docker test build to fail.
[Here](https://github.com/virtualmin/Virtualmin-Config/blob/83641806fe8205cd716472fe6c116c4815928e55/lib/Virtualmin/Config/Plugin/Net.pm#L48). 
It's during `Phase 3: Configuration`, `6/18 Configuring Net`.
`Error: Failed to replace /etc/resolv.conf with /etc/resolv.conf.webmintmp.3051 : Device or resource busy`

Need fix to get #61 and #35 working.

**Comment by swelljoe** [comment]
I've already told you this is removed, the new version just hasn't been pushed yet. You can see the change in the Virtualmin-Config repo. I'm not going to argue about it.

**Comment by chris001** [comment]
> You can see the change in the Virtualmin-Config repo.

I searched that repo, and couldn't find a branch with the `/etc/resolv.conf` removed from `Net.pm`.
Kindly share a link to `Net.pm` in the `Virtualmin-Config` repo with `/etc/resolv.conf` removed?

**Comment by iliajie** [comment]
It's in my latest PR that hasn't been merged yet.

**Comment by swelljoe** [comment]
Net does not run at all anymore in the next version (all Net.pm does is modify resolv.conf in a variety of ways). The necessary change is not in Ilia's PR. It is in a recent PR I made. Jebus. I'm not lying to you. It'll be gone when I roll an update.

Can we stop arguing about this?
