### ISSUE TITLE
17.04

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#7]
No support install on 17.04?  17.04 has been out for 6 months by now.

**Comment by andreychek** [comment]
Sorry, only the Ubuntu LTS releases are supported.

The non-LTS releases are only supported by Ubuntu for about 9 months, which makes them very difficult for us to support. 

If you're looking to run a server, we'd highly recommend an LTS release due to the longer support.

**Comment by chris001** [comment]
Yes but it's a development type of server, trying to use the newest latest packages, until 18.04 LTS in 6 months.

**Comment by andreychek** [comment]
Understood!

Unfortunately, we're not going to be able to provide support for non-LTS releases. They're a lot of work to keep up with, and there isn't enough demand to want to use them in a server environment.

Sorry!
