### ISSUE TITLE
2 shellcheck fails (SC1117).

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#70]
```
In virtualmin-install.sh line 808:
      rpm_release_files=$(echo "$rpm_release_files" | tr "\n" " ")
                                                          ^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".


In virtualmin-install.sh line 822:
      sed -i "s/http:\/\//https:\/\//" /etc/yum.repos.d/virtualmin.repo
                     ^-- SC1117: Backslash is literal in "\/". Prefer explicit escaping: "\\/".
                       ^-- SC1117: Backslash is literal in "\/". Prefer explicit escaping: "\\/".
                                ^-- SC1117: Backslash is literal in "\/". Prefer explicit escaping: "\\/".
                                  ^-- SC1117: Backslash is literal in "\/". Prefer explicit escaping: "\\/".
```
Note: `shellcheck` command was run on Debian 10.

**Comment by swelljoe** [comment]
This sed would probably be better off as something like `sed -i "s#http:#https:#"` anyway. Just a lot more readable than all those slashes. And, bypasses all the escaping bullshit.

I don't know about the tr. Might be better to temporarily set IFS to `\n` and loop over it directly, but maybe shellcheck would complain about that, too.

**Comment by swelljoe** [comment]
Odd that shellcheck on travis is not complaining.

**Comment by chris001** [comment]
Is possibly because different OS and version running in Travis vs Debian 10.

**Comment by iliajie** [comment]
@chris001 Check the [last commit](https://github.com/virtualmin/virtualmin-install/commit/d5c18a8dda27a230da2aef742a519ca6c2d5dc5a). I expect it will fix your issue.

**Comment by chris001** [comment]
@iliajie That works! One step closer to automatically test each PR and official Release by having Travis install on all supported OS!  #61 #35
