### ISSUE TITLE
Fails on CentOS 7

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#71]
```
Complete!
Checking and installing system packages updates: Success.
Spin pid is: 700
Error:
 Problem: package php-mysql-5.4.16-48.el7.x86_64 conflicts with php-mysqlnd provided by php-mysqlnd-5.4.16-48.el7.x86_64
  - conflicting requests
Installing dependencies and system packages: Failed with error: 1
[2022-06-07 04:04:09 UTC] [ERROR] Something went wrong with the previous command. Exiting.
```
This error comes from running the current latest version from the repo, `./virtualmin-install.sh --minimal --bundle LEMP` on centos 7 docker image, to test if it works on all supported OS versions.

**Comment by swelljoe** [comment]
Don't preinstall packages.

**Comment by chris001** [comment]
Only preinstalling `perl` and utilities like `sudo wget`, no `php` or `mysql`.  Does this mean the CentOS 7 docker image includes that `php-mysql` package?

**Comment by chris001** [comment]
```
$ yum install -y php-mysql
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.mirror.constant.com
 * epel: ftp.cse.buffalo.edu
 * extras: mirror.team-cymru.com
 * updates: mirror.team-cymru.com
Resolving Dependencies
--> Running transaction check
---> Package php-mysql.x86_64 0:5.4.16-48.el7 will be installed
--> Processing Dependency: libmysqlclient.so.18(libmysqlclient_18)(64bit) for package: php-mysql-5.4.16-48.el7.x86_64
--> Processing Dependency: libmysqlclient.so.18()(64bit) for package: php-mysql-5.4.16-48.el7.x86_64
--> Running transaction check
---> Package mariadb-libs.x86_64 1:5.5.68-1.el7 will be installed
--> Processing Conflict: php-mysql-5.4.16-48.el7.x86_64 conflicts php-mysqlnd
--> Finished Dependency Resolution
Error: php-mysql conflicts with php-mysqlnd-5.4.16-48.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
Looks like it tries and fail to install `php-mysql`, however conflicts with `php-mysqlnd` the newer one which is installed already on this official current CentOS 7 image, either needs more flags to make `php-mysql` install, or just allow the error to happen without exiting, and continue `install.sh`.

**Comment by iliajie** [comment]
Yeah, this was a bug in our yum-groups. [Fixed](https://github.com/virtualmin/virtualmin-yum-groups/commit/af301d7a3346447c9b73e47a72d696ceb9d6626a) now.

**Comment by chris001** [comment]
Does [virtualmin-yum-groups](https://github.com/virtualmin/virtualmin-yum-groups/) have to get made into a [new release](https://github.com/virtualmin/virtualmin-yum-groups/releases) for that [fix](https://github.com/virtualmin/virtualmin-yum-groups/commit/af301d7a3346447c9b73e47a72d696ceb9d6626a) to get used by the [installer script](https://github.com/virtualmin/virtualmin-install)?

**Comment by iliajie** [comment]
Yes, Joe should push a change.
