### ISSUE TITLE
Post-installation wizard fail

### ISSUE THREAD

**Issue by geass88** [virtualmin/virtualmin-install#72]
I tried to install the RC9 version from the master branch on Almalinux 8.6; this message appears and the procedure stops.

![Schermata del 2022-06-08 09-15-36](https://user-images.githubusercontent.com/1718453/172590785-09d6a301-a3aa-40da-b6b8-c9a66f561130.png)

**Comment by iliajie** [comment]
Yes, unfortunately there was a bug in Webmin 1.994, which is going to be fixed in upcoming Webmin 1.995.

Meanwhile, the fix can be found here - https://forum.virtualmin.com/t/how-to-install-virtualmin-on-almalinux/115065/18?u=ilia
