### ISSUE TITLE
Input from keyboard not working with the latest installation script

### ISSUE THREAD

**Issue by ADDISON74** [virtualmin/virtualmin-install#75]
I am running Ubuntu 22 in a virtual machine for testing different packages. 

I downloaded ```virtualmin-install.sh``` file from the master branch and I wanted to install it. The script is running but when it asks to enter y/n option in terminal window there is no letter displayed. After ```Ctrl + C``` it starts to install although I couldn't enter y/n but it gets stuck at Phase 2 "Installing Virtualmin 7 and all related packages".

I downloaded ```virtualmin-install.sh``` file from the dev/support-grade-b-systems branch and I was able to install Virtualmin on Ubuntu 22 without any issues.

The installation file in the master branch was modified 3 days ago from what I can see. Has anyone faced this situation when you want to enter from the keyboard and what you enter does not appear in the window? Thank you.

**Comment by iliajie** [comment]
This is expected.

The work around for now would be to change download URL to `.slib` inside of `virtualmin-install.sh` script to `https://raw.githubusercontent.com/virtualmin/slib/master/slib.sh` ..

**Comment by iliajie** [comment]
This is done so a user wouldn't be able to break the look of installation process by typing. So, the user input is disabled by default and re-enabled only upon actual input ..

**Comment by ADDISON74** [comment]
Thank you Ilia for your reply. I realized that the user was not supposed to enter anything from the keyboard during the installation. But the issue occurs when the script asks you to enter an option and you can't do it. For example, in the image below I cannot give an answer to the question ```Continue? (y/n)``. Enter key still works.

![screenshot](https://user-images.githubusercontent.com/8360474/183289294-d9d0bb6e-0187-4fd7-b439-31c494fe51bb.jpg)

**Comment by iliajie** [comment]
I am sorry I wasn't clear before, as I though I have answered your question. Look, after you grabbed `virtualmin-install.sh`, you need to open it for an edit and replace:

```
$download "https://$upgrade_virtualmin_host/lib/slib.sh" >>$log 2>&1
```

to

```
$download "https://raw.githubusercontent.com/virtualmin/slib/master/slib.sh" >>$log 2>&1
```

.. for testing purposes. After Virtualmin 7 installer is released, that won't be needed.
