### ISSUE TITLE
script not interactive?

### ISSUE THREAD

**Issue by Lawkss** [virtualmin/virtualmin-install#76]
Hello, sorry if this is most likely not a real issue. 

But how do I make the script interactive? If I download the script from github, and the installer asks me for input, I am unable to do so.

if I download the one from the forums it works fine with y/n inputs and everything. But from github I cannot enter anything. 

I really need the recent one working to get the skip-broken functionality. 

When install fails on almalinux for awstats can I rerun the current script? or do I need to reinstall the server.

**Comment by swelljoe** [comment]
I have no idea what you mean. You don't get an error? What shell are you running it in?

**Comment by Lawkss** [comment]
When I download this file:
https://software.virtualmin.com/gpl/scripts/vm7-beta-install.sh

and run /bin/sh vm7-beta-install.sh

the script will ask me Continue Y/n? and I can type Y.

If I download the more recent script from:
https://github.com/virtualmin/virtualmin-install/raw/master/virtualmin-install.sh

the script will ask me Continue Y/n? and I cannot type anything. I can hit enter to continue. But it will not allow any other input. No letters. So I cannot use it, for example to type the fully qualified domain name.

**Comment by Lawkss** [comment]
It works but it seems to treat all text like a password where you cannot see what you type.

**Comment by swelljoe** [comment]
I'm gonna close this, as it seems unlikely to remain an issue. I'm sure we would have heard loud complaints if the script didn't work for some folks on Alma.

I assume this was being run in a non-interactive terminal or something (like the old Command Prompt/pop shell in Webmin, prior to version 2.013).
