### ISSUE TITLE
Keyboard local echo is off after answering no to "Continue? (y/n)"

### ISSUE THREAD

**Issue by SamSirry** [virtualmin/virtualmin-install#77]
As the installer starts, checks the system, etc, it asks whether to continue to start the installation.
If No is answered the installer is terminated but the keyboard's local echo is not restored; typing anything at the bash prompt is in secret ink.

OS: Debian 11, fresh installation, updated.
Terminal: PuTTY 0.76 on Windows 10

**Comment by iliajie** [comment]
Hello. This is expected.

Explained in a this dupe - https://github.com/virtualmin/virtualmin-install/issues/75

**Note:** Please keep it opened until we finally release Virtualmin 7.
