### ISSUE TITLE
Option to install MySQL instead of MariaDB

### ISSUE THREAD

**Issue by PitWenkin** [virtualmin/virtualmin-install#78]
Would it be possible to add an option to the installer to install MySQL instead of MariaDB
e.g. `--database | -d <MariaDB|MySQL> choose database to install (defaults to MariaDB)`

**Comment by iliajie** [comment]
Hello, 

Well, I wouldn't mind adding it. It doesn't seem to be a difficult task. Although, I don't understand the reason behind, i.e. why anyone would want to do it?

**Comment by PitWenkin** [comment]
> Although, I don't understand the reason behind, i.e. why anyone would want to do it?

For compatibility/coherence reasons.
We are running mulitple servers, and each should have the exact same modules

**Comment by iliajie** [comment]
Next Virtualmin install script release will allow to pre-install MySQL and have it kept (not to be replaced with MariaDB).

**Comment by PitWenkin** [comment]
When will the next release be? ;)

**Comment by iliajie** [comment]
This is already possible to do.

**Comment by PitWenkin** [comment]
Sorry but neither the  `--help` option of the installer, nor the source of the [installer ](https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh) point to that being possible. 

Using `--database` only shows the help text.
The only reference to MySQL is a check if it is already preconfigured …

The [documentation](https://www.virtualmin.com/documentation/installation/manual/) references MySQL, but his would mean a complete manual installation …

I however found something in https://software.virtualmin.com/vm/7/gpl/apt/dists/virtualmin/main/binary-all/Packages, which seems to indicate that as of version `7.0.4-1` of `virtualmin-lamp-stack` `mariadb `and `mysql `are both valid dependencies (If I understood that correctly). I think that this was a prerequisite to implement the feature I was asking here?

**Comment by iliajie** [comment]
You can simply install `mysql-common`, `mysql-server` and `mysql-client` prior Virtualmin installation and it would work.



> Using `--database` only shows the help text.

I think @swelljoe didn't want much to add `--database` option. If Joe agrees I could (I think) easily add it.

**Comment by swelljoe** [comment]
I really don't like adding options that make it seem like either is a recommended and supported choice. We're trying to reduce our surface area, the number of things we have to support. Offering an installer option for MySQL implies an obligation to support MySQL, which I don't want to keep doing, as it has become much more expensive (time/resources-wise) to support MySQL than MariaDB, as MySQL has begun breaking backward compatibility and compatibility with MariaDB in every major version in ways that require development work from us.

I can't stop them from breaking things, but I can discourage people from using MySQL by making it not seem like an equally valid path.

I'd be OK documenting _how_ to do it (just preinstall it, I think). But, I really want to remove the expectation that we are going to be able to provide good customer support for MySQL going forward. I used to be completely neutral on this, but they keep breaking stuff, so I'm no longer neutral.

**Comment by PitWenkin** [comment]
Thanks, I can live with that workaround. I now understand @iliajie's reply as a short form of your answer.

If it was documented would even be better.
