### ISSUE TITLE
16.04 install errors.

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-install#8]
```
23 Oct 15:12:20 ntpdate[29224]: Can't adjust the time of day: Operation not permitted
```

```
Use of uninitialized value $clocksource in string eq at /usr/share/perl5/Virtualmin/Config/Plugin/NTP.pm line 35.
Use of uninitialized value $clocksource in string eq at /usr/share/perl5/Virtualmin/Config/Plugin/NTP.pm line 38.
```

```
The filesystem / could not be remounted with quotas enabled.
You may need to reboot your system, and/or enable quotas in the Disk
Quotas module.
```

**Comment by jcameron** [comment]
Are you running Webmin on a real machine, or a VM of some kind? Because from that error message, it sounds like you're on a VM for which setting the time of day isn't possible.

**Comment by chris001** [comment]
Yes it's an OpenVZ VM running 16.04.  The `uninitialized value $clocksource` error looks like a bug though - it should initialize the value, or catch that error.

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next release of the virtualmin-config code.
