### ISSUE TITLE
RHEL 9.1 installation issue - installation hangs at [4/21] Configuring ClamAV

### ISSUE THREAD

**Issue by pixel-paul** [virtualmin/virtualmin-install#80]
I'm encountering an issue installing Virtualmin on a RHEL 9.1 KVM guest. The installation is hanging at the 'Configuring ClamAV' step.

I am using v7.0.1 of the install script.

<img width="583" alt="Screenshot 2022-11-29 at 13 36 49" src="https://user-images.githubusercontent.com/389303/204544589-de62c999-85ae-4421-b2ec-c396fc75982f.png">

Here is the log output:

[virtualmin-install.log](https://github.com/virtualmin/virtualmin-install/files/10113658/virtualmin-install.log)

**Comment by iliajie** [comment]
Hello,

How much RAM you have? Also, if you login using SSH on the separate tab and run `freshclam` .. what happens?

**Comment by pixel-paul** [comment]
Hi @iliajie,

You got it - the connection to ClamAV was being blocked by a firewall.

Thanks!

Paul

**Comment by iliajie** [comment]
In which way it was blocked? What did you do exactly to unblock it?

**Comment by pixel-paul** [comment]
It was blocked by an edge firewall's IDS as there must have been a very large number connections made to download the files (like >10000 in 10 seconds!). This then triggered a possible ACK flood DDOS, blocking the IP address - this is therefore unrelated to Virtualmin. I've encountered this before during large software updates, just not with freshclam.

Sorry about this, I even thought to check if this was a problem yesterday and completely forgot about it.

**Comment by iliajie** [comment]
Alright, thanks for the details.
