### ISSUE TITLE
Rename `install.sh` to `virtualmin-install.sh` everywhere

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-install#81]
We've decided that it would be better to call `install.sh` `virtualmin-install.sh` (decided a long time ago, which is why it's named `virtualmin-install.sh` in this repo.

In order to make that change everywhere, though, we need all documentation to be updated to refer to `virtualmin-install.sh` instead of `install.sh`. Plus we need all download links to be updated. That's a lot of stuff.

**Comment by swelljoe** [comment]
Finding mentions of install.sh:

https://www.virtualmin.com/?s=%22install.sh%22

**Comment by iliajie** [comment]
I think it's all updated.
