### ISSUE TITLE
Unable to determine IP address of primary interface.

### ISSUE THREAD

**Issue by v0UwUK6CmCrjVB1PAtRb** [virtualmin/virtualmin-install#84]
When installing Virtualmin on an OpenVZ 7 VPS (the VPS runs AlmaLinux 8), Virtualmin will prompt:

```
[root@test ~]# ./install.sh -f
Running Virtualmin 7 pre-installation setup:
  Updating CA certificates ..
  .. done
[INFO] Started installation log in /root/virtualmin-install.log
▣◻◻ Phase 1 of 3: Setup
Device "link" does not exist.
[WARNING] Unable to determine IP address of primary interface.
Please enter the name of your primary network interface:
```

I have to input `venet0` each time (always the default for OpenVZ 7).

It would be handy if Virtualmin could detect the presence of OpenVZ virtualization and handle this automatically.

`hostnamectl status` can detect that quite easily:

```
[root@test ~]# hostnamectl status
   Static hostname: test.test.com
         Icon name: computer-container
           Chassis: container
        Machine ID: e89c30c290624b4ca86ab1aae440cd5b
           Boot ID: 97c4b86682aa4c9697bc825f904372f7
    Virtualization: openvz
  Operating System: AlmaLinux 8.7 (Stone Smilodon)
       CPE OS Name: cpe:/o:almalinux:almalinux:8::baseos
            Kernel: Linux 4.18.0
      Architecture: x86-64
[root@test ~]#
```

Also, it doesn't just ask for it to be inputted once, but twice.

Here is the full install log: https://pastebin.com/raw/t05nMWsh

Also note:

```
./slib.sh: line 465: log_debugPrimary address detected as 127.0.0.1: command not found
```
```
Use of uninitialized value $backend in concatenation (.) or string at /usr/share/perl5/vendor_perl/Virtualmin/Config/Plugin/Fail2banFirewalld.pm line 90.
```

**Comment by iliajie** [comment]
Hello,

> Device "link" does not exist.
> [WARNING] Unable to determine IP address of primary interface.
> Please enter the name of your primary network interface:

What is the output of the following commands on your system:

```
ip ro ls
```

and 

```
ip -f inet addr show
```

**Comment by iliajie** [comment]
Your system doesn't have any active network interfaces configured. Fix that and it will work for you.
