### ISSUE TITLE
Install script fails on Debian 11.6 (no /etc/webmin after webmin package instalation)

### ISSUE THREAD

**Issue by dkavlakov** [virtualmin/virtualmin-install#85]
Hello
I want to migrate Virtualmin Pro to new server, Unfortuanally on Debian 11.6 both GPL and Pro install scripts fail imedeately after installing Webmin. The reason is that none of the webmin packages currently in repository creates /etc/webmin and it's contents, while both webmin and alll packages that depend on iit fail because of /etc/webmin's absence.

**Comment by jcameron** [comment]
Seems like the Webmin install is failing, probably because it can't detect the OS version properly. What does `/etc/debian_version` contain on this system?

**Comment by dkavlakov** [comment]
11.6

**Comment by jcameron** [comment]
Ok ... and what Webmin version was being installed?

**Comment by dkavlakov** [comment]
Tried all Webmin versions in the repository.
Found something really weird in the end.Both Webmin and Usermin fail to install their respective /etc folders if run as root or from a script that runs as root. When run by user with sudo however they install their /etc folders successfuly.

**Comment by jcameron** [comment]
That's really odd! Are you sure it was actually running as root?

**Comment by dkavlakov** [comment]
Yes, i am not bubuntisation fan and prefer to have strict policies set for sudo when installed, while using su to work as root when really needed. Because of this i hat to explctly allow myself to run apt with sudo instead of as root.
Actually i got the idea to try it this way because of the root check block in your instalation script that is also made to fail if you run the script as root, but works fine if you run it as user with sudo.

**Comment by jcameron** [comment]
Does the setup script output any more detailed error message when it fails? It might be logged `/tmp/.webmin/webmin-setup.out`
