### ISSUE TITLE
MySQL instead of MariaDb

### ISSUE THREAD

**Issue by robouden** [virtualmin/virtualmin-install#87]
Thanks for having this script on GitHub.

After trying to use the official installer script and noticed that the MySQL version uses only MariaDB, I like to know if someone has tested this script and was able to install MySQL instead of MariaDB.
I want to install VirualMin with MySQL on Ubuntu 22.04 (so I can run the WordPress installer script) is that possible?

Regards,
Rob Oudendijk

**Comment by robouden** [comment]
Wooooo.. So happy..!!!

The installer script from this repo does NOT use MariaDB as default. I had first setup, for being sure, MySQL manually by APT and all works fine now.

Regards,
Rob Oudendijk

**Comment by iliajie** [comment]
> I want to install Virualmin with MySQL on Ubuntu 22.04 (so I can run the WordPress installer script)

WordPress works just fine with MariaDB.

> I had first setup, for being sure, MySQL manually by APT and all works fine now.

Yes, the latest Virtualmin installer won't switch to MariaDB, if MySQL was pre-installed.

**Comment by robouden** [comment]
Problem is that the installation script of VirtualMin for WordPress does not seem to work correctly when MariaDB is activated.

Regards,
Rob Oudendijk

**Comment by iliajie** [comment]
> Problem is that the installation script of VirtualMin for WordPress does not seem to work correctly when MariaDB is activated.

What error do you get exactly when using MySQL?

**Comment by robouden** [comment]
No errors anymore since I in stalled MySQL first and then run the installation script for Virtualmin.

**Comment by robouden** [comment]
Similar to https://archive.virtualmin.com/node/68335
