### ISSUE TITLE
Give the possibility of choice between MariaDB and MySQL

### ISSUE THREAD

**Issue by ljdj** [virtualmin/virtualmin-install#92]
Good morning,
Sorry if the translation is not good, but I am French.

Virtualmin is very well done (since version 6 on ubunutu 18.04 lts with MySQL)!

I'm currently on the new Ubuntu 22.04lts!
Please leave the possibility to choose => create a variable, select or modify the script for (MySQL or MariaDB)

Personally, I don't like MariaDB!

I'm going to go back to 18.04 TLS with the old v6 script that I kept for myself, because it was on MySQL!

Even if I modified the script, flipped it in all directions, mariabd installed directly!

Virtialmin-install.sh MySQL receives an error because MariaDb installs automatically!

To be defined in the script if possible.

Thanks in advance, because I've been playing with installing and reinstalling unbuntu and modifying the script for 3 days!

This can no longer continue because on the virtualmin forum some people are complaining about this defect in the configuration.

Please take this note into account because some people like me use MySQL.

Please do what is necessary to choose between the 2!
just like Apache and Engnix!

Thank you for your answers and future modifications on the subjects mentioned in this request.

Sincerely.

**Comment by iliajie** [comment]
Hello,

We could technically enroll support for choosing database type in Virtualmin installer.

Although, it is not a problem already to pre-install MySQL before running `virtualmin-install.sh` script to make it work flawlessly by running:

```
apt-get install mysql-server mysql-client mysql-common
```

**Comment by ljdj** [comment]
I have already made this order I get an error

![Screen Shot 11-09-23 at 01 11 AM](https://github.com/virtualmin/virtualmin-install/assets/2798392/e036403e-a01e-458b-9612-4408a16ac584)

Everyone complains about the defect of not being able to choose their database so we will have to react a little!

I have the latest master version of the master script.

If it's too complicated to create scripts for each version, then offer a script and during installation, offer either mdb or mysql!

If there are no positive responses, I will have to give bad publicity!

From the beginning it was always MySQL by default and in the script before v7!

Strange that V7 requires MariaBD (personally I can't supervise it)

Please leave a field in the script for the version (MySQL or MariaDB)

It's up to you to do the right thing, it's not up to users to come and cry all the time!

I would like a lamp script (apache, MySQL) to help you with updates!

So that everyone can do the installation they want and not depend on a preconfigured script

**Comment by ljdj** [comment]
If the problem comes from the fact that the developers are not paid, just for a modification of the script(s) I can make a symbolic donation of 1€ to them, as a good friend!

I like virtualmin, but since v7 and addition of MariaDB office, this cannot continue.

**Comment by swelljoe** [comment]
A friend doesn't ask someone to put in hours of work for 1 euro and a bunch of demands.

**Comment by swelljoe** [comment]
If you're unwilling to run a couple of extra commands in order to use MySQL, you're cordially invited to use something else.

**Comment by swelljoe** [comment]
> If there are no positive responses, I will have to give bad publicity!

Fuck you. Truly. Fuck off. We don't owe you anything.

**Comment by ljdj** [comment]
Je n'ai pas fini la discutions !

Soit, tu rouvres le post, soit je fait ban virtualmin de github pour faute de réponses réel et fondé !

Moi, je souhaite MYSQL et nonMARIADB( maria debil) !
À vous de faire les modifications pour tous les utilisateurs, car perso sur le forum virtualmin, beaucoup de personnes n'aime pas MariDB!

À vous de faire le choix entre la possibilité de choisir en brut dans le scritp mysql ou mariadb peu de modification à effectuer !

Les utilisateurs en on marre de se faire lock le post post pour un truc que les dev peuvent modifier en 5 minutes

**Comment by swelljoe** [comment]
Threats will only be answered with profanity and disdain. You cannot dictate how we spend our time or how we develop our projects and make threats if we don't do what you want. We owe you nothing, and I can't understand how you believe your behavior is acceptable. Do you go around making threats to everyone, or just the people who've spent decades building the software you get to use for free?

The discussion _is_ over, and your opinions on the topic are no longer welcome.

**Comment by ljdj** [comment]
> > If there are no positive responses, I will have to give bad publicity!
> 
> Fuck you. Truly. Fuck off. We don't owe you anything.

oui j'aime ca et toi?

répond inteligament et non part grossiereté!

je vous ai insultez?
a priori non donc je transment a github pour ban
